// Source: Orthodox Menologion fixed-date saints
// Do not edit manually.

/**
 * Fixed-date saints from the Orthodox Menologion.
 * All dates are Julian calendar.
 * Total: 592 entries
 */
export const VENERATED_SAINTS = [

	// ─── JANUARY ───────────────────────────────────
	{
		name: "Basil the Great, Archbishop of Caesarea of Cappadocia",
		nameEl: "Βασίλειος ο Μέγας, Αρχιεπίσκοπος Καισαρείας Καππαδοκίας",
		nameId: "Js. Basilius Agung, Uskup Agung Kaisarea Kapadokia",
		julianMonth: 1,
		julianDay: 1,
	},
	{
		name: "Veneration of Silvester, Pope of Rome",
		nameEl: "Μνήμη Σιλβέστρου, Πάπα Ρώμης",
		nameId: "Peringatan Js. Silvester, Paus Roma",
		julianMonth: 1,
		julianDay: 2,
	},
	{
		name: "Holy Martyr Gordios",
		nameEl: "Άγιος Μάρτυς Γόρδιος",
		nameId: "Martir Kudus Gordios",
		julianMonth: 1,
		julianDay: 3,
	},
	{
		name: "Prophet Malachia",
		nameEl: "Προφήτης Μαλαχίας",
		nameId: "Nabi Maleakhi",
		julianMonth: 1,
		julianDay: 3,
	},
	{
		name: "Venerable Theoktistos, Hegumen of Cucume",
		nameEl: "Όσιος Θεόκτιστος, Ηγούμενος Κουκουμίου",
		nameId: "Js. Theoktistos, Hegumen Kukume",
		julianMonth: 1,
		julianDay: 4,
	},
	{
		name: "Venerable Syncletica",
		nameEl: "Οσία Συγκλητική",
		nameId: "Js. Sinkletika",
		julianMonth: 1,
		julianDay: 5,
	},
	{
		name: "Holy Martyr Theonas",
		nameEl: "Άγιος Μάρτυς Θεωνάς",
		nameId: "Martir Kudus Theonas",
		julianMonth: 1,
		julianDay: 5,
	},
	{
		name: "Holy Martyr Theopemptos",
		nameEl: "Άγιος Μάρτυς Θεόπεμπτος",
		nameId: "Martir Kudus Theopemptos",
		julianMonth: 1,
		julianDay: 5,
	},
	{
		name: "Venerable Dominica",
		nameEl: "Οσία Δομνίκα",
		nameId: "Js. Dominika",
		julianMonth: 1,
		julianDay: 8,
	},
	{
		name: "Holy Martyr Polyeuktos",
		nameEl: "Άγιος Μάρτυς Πολύευκτος",
		nameId: "Martir Kudus Polyeuktos",
		julianMonth: 1,
		julianDay: 9,
	},
	{
		name: "Venerable Dometian, Bishop of Melitene",
		nameEl: "Όσιος Δομετιανός, Επίσκοπος Μελιτηνής",
		nameId: "Js. Dometian, Uskup Melitene",
		julianMonth: 1,
		julianDay: 10,
	},
	{
		name: "Veneration of Gregory, Bishop of Nyssa",
		nameEl: "Μνήμη Γρηγορίου, Επισκόπου Νύσσης",
		nameId: "Peringatan Js. Gregorius, Uskup Nisa",
		julianMonth: 1,
		julianDay: 10,
	},
	{
		name: "Venerable Marcian",
		nameEl: "Όσιος Μαρκιανός",
		nameId: "Js. Markian",
		julianMonth: 1,
		julianDay: 10,
	},
	{
		name: "Venerable Theodosius the Cenobiarch",
		nameEl: "Όσιος Θεοδόσιος ο Κοινοβιάρχης",
		nameId: "Js. Theodosios sang Kenobiarkh",
		julianMonth: 1,
		julianDay: 11,
	},
	{
		name: "Holy Martyr Tatiana",
		nameEl: "Αγία Μάρτυς Τατιανή",
		nameId: "Martir Kudus Tatiana",
		julianMonth: 1,
		julianDay: 12,
	},
	{
		name: "Holy Martyr Hermylos",
		nameEl: "Άγιος Μάρτυς Ερμύλος",
		nameId: "Martir Kudus Hermylos",
		julianMonth: 1,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Stratonikos",
		nameEl: "Άγιος Μάρτυς Στρατόνικος",
		nameId: "Martir Kudus Stratonikos",
		julianMonth: 1,
		julianDay: 13,
	},
	{
		name: "Venerable John the Hut-Dweller",
		nameEl: "Όσιος Ιωάννης ο Καλυβίτης",
		nameId: "Js. Yohanes sang Penghuni Gubuk",
		julianMonth: 1,
		julianDay: 15,
	},
	{
		name: "Venerable Paul of Thebes",
		nameEl: "Όσιος Παύλος ο Θηβαίος",
		nameId: "Js. Paulus dari Theba",
		julianMonth: 1,
		julianDay: 15,
	},
	{
		name: "Venerable Anthony the Great",
		nameEl: "Όσιος Αντώνιος ο Μέγας",
		nameId: "Js. Antonius Agung",
		julianMonth: 1,
		julianDay: 17,
	},
	{
		name: "Return from Exile of Athanasius, Archbishop of Alexandria",
		nameEl: "Επάνοδος εκ της εξορίας Αθανασίου, Αρχιεπισκόπου Αλεξανδρείας",
		nameId: "Kepulangan dari Pengasingan Js. Athanasius, Uskup Agung Aleksandria",
		julianMonth: 1,
		julianDay: 18,
	},
	{
		name: "Veneration of Cyril, Archbishop of Alexandria",
		nameEl: "Μνήμη Κυρίλλου, Αρχιεπισκόπου Αλεξανδρείας",
		nameId: "Peringatan Js. Kyrilos, Uskup Agung Aleksandria",
		julianMonth: 1,
		julianDay: 18,
	},
	{
		name: "Veneration of Arsenios of Corcyra",
		nameEl: "Μνήμη Αρσενίου της Κερκύρας",
		nameId: "Peringatan Js. Arsenios dari Korkyra",
		julianMonth: 1,
		julianDay: 19,
	},
	{
		name: "Venerable Makarios the Egyptian",
		nameEl: "Όσιος Μακάριος ο Αιγύπτιος",
		nameId: "Js. Makarios dari Mesir",
		julianMonth: 1,
		julianDay: 19,
	},
	{
		name: "Venerable Euthymius the Great",
		nameEl: "Όσιος Ευθύμιος ο Μέγας",
		nameId: "Js. Euthymius Agung",
		julianMonth: 1,
		julianDay: 20,
	},
	{
		name: "Venerable Maximos the Confessor",
		nameEl: "Όσιος Μάξιμος ο Ομολογητής",
		nameId: "Js. Maximos sang Pengaku Iman",
		julianMonth: 1,
		julianDay: 21,
	},
	{
		name: "Holy Martyr Neophytos",
		nameEl: "Άγιος Μάρτυς Νεόφυτος",
		nameId: "Martir Kudus Neophytos",
		julianMonth: 1,
		julianDay: 21,
	},
	{
		name: "Holy Hosiomartyr Anastasius the Persian",
		nameEl: "Άγιος Οσιομάρτυς Αναστάσιος ο Πέρσης",
		nameId: "Hosiomartir Kudus Anastasius dari Persia",
		julianMonth: 1,
		julianDay: 22,
	},
	{
		name: "Holy Apostle Timon",
		nameEl: "Άγιος Απόστολος Τίμων",
		nameId: "Rasul Kudus Timon",
		julianMonth: 1,
		julianDay: 22,
	},
	{
		name: "Holy Apostle Timothy",
		nameEl: "Άγιος Απόστολος Τιμόθεος",
		nameId: "Rasul Kudus Timotius",
		julianMonth: 1,
		julianDay: 22,
	},
	{
		name: "Holy Hieromartyr Clement of Ancyra",
		nameEl: "Άγιος Ιερομάρτυς Κλήμης Αγκύρας",
		nameId: "Hieromartir Kudus Klemens dari Ankyra",
		julianMonth: 1,
		julianDay: 23,
	},
	{
		name: "Venerable Xenia",
		nameEl: "Οσία Ξένη",
		nameId: "Js. Ksenia",
		julianMonth: 1,
		julianDay: 24,
	},
	{
		name: "Gregory the Theologian, Archbishop of Constantinople",
		nameEl: "Γρηγόριος ο Θεολόγος, Αρχιεπίσκοπος Κωνσταντινουπόλεως",
		nameId: "Js. Gregorius sang Teolog, Uskup Agung Konstantinopel",
		julianMonth: 1,
		julianDay: 25,
	},
	{
		name: "Venerable Xenophon",
		nameEl: "Όσιος Ξενοφών",
		nameId: "Js. Ksenofon",
		julianMonth: 1,
		julianDay: 26,
	},
	{
		name: "Venerable Ephrem the Syrian",
		nameEl: "Όσιος Εφραίμ ο Σύρος",
		nameId: "Js. Efrem dari Siria",
		julianMonth: 1,
		julianDay: 28,
	},
	{
		name: "Gregory the Theologian, Archbishop of Constantinople",
		nameEl: "Γρηγόριος ο Θεολόγος, Αρχιεπίσκοπος Κωνσταντινουπόλεως",
		nameId: "Js. Gregorius sang Teolog, Uskup Agung Konstantinopel",
		julianMonth: 1,
		julianDay: 30,
	},
	{
		name: "Holy Hieromartyr Hippolytus",
		nameEl: "Άγιος Ιερομάρτυς Ιππόλυτος",
		nameId: "Hieromartir Kudus Hippolytus",
		julianMonth: 1,
		julianDay: 30,
	},
	{
		name: "John Chrysostom, Archbishop of Constantinople",
		nameEl: "Ιωάννης ο Χρυσόστομος, Αρχιεπίσκοπος Κωνσταντινουπόλεως",
		nameId: "Js. Yohanes Krisostomus, Uskup Agung Konstantinopel",
		julianMonth: 1,
		julianDay: 30,
	},
	{
		name: "Holy Unmercenary Cyrus",
		nameEl: "Άγιος Ανάργυρος Κύρος",
		nameId: "Kudus Tanpa Bayaran Kyrus",
		julianMonth: 1,
		julianDay: 31,
	},
	{
		name: "Holy Unmercenary John",
		nameEl: "Άγιος Ανάργυρος Ιωάννης",
		nameId: "Kudus Tanpa Bayaran Yohanes",
		julianMonth: 1,
		julianDay: 31,
	},

	// ─── FEBRUARY ───────────────────────────────────
	{
		name: "Holy Martyr Tryphon",
		nameEl: "Άγιος Μάρτυς Τρύφων",
		nameId: "Martir Kudus Trifon",
		julianMonth: 2,
		julianDay: 1,
	},
	{
		name: "Veneration of Righteous Simeon who Received God",
		nameEl: "Μνήμη Δικαίου Συμεών του Θεοδόχου",
		nameId: "Peringatan Js. Simeon yang Menerima Allah",
		julianMonth: 2,
		julianDay: 3,
	},
	{
		name: "Venerable Isidore of Pelusium",
		nameEl: "Όσιος Ισίδωρος ο Πηλουσιώτης",
		nameId: "Js. Isidorus dari Pelusium",
		julianMonth: 2,
		julianDay: 4,
	},
	{
		name: "Venerable Bukolos, Bishop of Smyrna",
		nameEl: "Όσιος Βουκόλος, Επίσκοπος Σμύρνης",
		nameId: "Js. Bukolos, Uskup Smirna",
		julianMonth: 2,
		julianDay: 6,
	},
	{
		name: "Holy Martyr Julian, a physician of Emesa",
		nameEl: "Άγιος Μάρτυς Ιουλιανός, Ιατρός εξ Εμέσης",
		nameId: "Martir Kudus Julian, tabib dari Emesa",
		julianMonth: 2,
		julianDay: 6,
	},
	{
		name: "Venerable Luke of Stirion",
		nameEl: "Όσιος Λουκάς ο εν Στειρίω",
		nameId: "Js. Lukas dari Stirion",
		julianMonth: 2,
		julianDay: 7,
	},
	{
		name: "Venerable Parthenios, Bishop of Lampascus",
		nameEl: "Όσιος Παρθένιος, Επίσκοπος Λαμψάκου",
		nameId: "Js. Parthenios, Uskup Lampsakus",
		julianMonth: 2,
		julianDay: 7,
	},
	{
		name: "Holy Great Martyr Theodore the Leader of Armies",
		nameEl: "Άγιος Μεγαλομάρτυς Θεόδωρος ο Στρατηλάτης",
		nameId: "Martir Agung Kudus Theodorus sang Panglima",
		julianMonth: 2,
		julianDay: 8,
	},
	{
		name: "Prophet Zacharias",
		nameEl: "Προφήτης Ζαχαρίας",
		nameId: "Nabi Zakharia",
		julianMonth: 2,
		julianDay: 8,
	},
	{
		name: "Holy Martyr Nicephoros",
		nameEl: "Άγιος Μάρτυς Νικηφόρος",
		nameId: "Martir Kudus Nikephoros",
		julianMonth: 2,
		julianDay: 9,
	},
	{
		name: "Holy Hieromartyr Charalampos",
		nameEl: "Άγιος Ιερομάρτυς Χαράλαμπος",
		nameId: "Hieromartir Kudus Kharalampos",
		julianMonth: 2,
		julianDay: 10,
	},
	{
		name: "Holy Hieromartyr Blaise, Bishop of Sebastea in Armenia",
		nameEl: "Άγιος Ιερομάρτυς Βλάσιος, Επίσκοπος Σεβαστείας Αρμενίας",
		nameId: "Hieromartir Kudus Blasius, Uskup Sebastea di Armenia",
		julianMonth: 2,
		julianDay: 11,
	},
	{
		name: "Veneration of Meletios, Archbishop of Antioch",
		nameEl: "Μνήμη Μελετίου, Αρχιεπισκόπου Αντιοχείας",
		nameId: "Peringatan Js. Meletios, Uskup Agung Antiokhia",
		julianMonth: 2,
		julianDay: 12,
	},
	{
		name: "Venerable Martinian",
		nameEl: "Όσιος Μαρτινιανός",
		nameId: "Js. Martinian",
		julianMonth: 2,
		julianDay: 13,
	},
	{
		name: "Venerable Auxentios",
		nameEl: "Όσιος Αυξέντιος",
		nameId: "Js. Auxentios",
		julianMonth: 2,
		julianDay: 14,
	},
	{
		name: "Venerable Maron the Hermit",
		nameEl: "Όσιος Μάρων ο Ερημίτης",
		nameId: "Js. Maron sang Pertapa",
		julianMonth: 2,
		julianDay: 14,
	},
	{
		name: "Holy Apostle Onesimos",
		nameEl: "Άγιος Απόστολος Ονήσιμος",
		nameId: "Rasul Kudus Onesimus",
		julianMonth: 2,
		julianDay: 15,
	},
	{
		name: "Holy Martyr Pamphilos",
		nameEl: "Άγιος Μάρτυς Πάμφιλος",
		nameId: "Martir Kudus Pamphilos",
		julianMonth: 2,
		julianDay: 16,
	},
	{
		name: "Holy Great Martyr Theodore of Tyre",
		nameEl: "Άγιος Μεγαλομάρτυς Θεόδωρος ο Τήρων",
		nameId: "Martir Agung Kudus Theodorus dari Tirus",
		julianMonth: 2,
		julianDay: 17,
	},
	{
		name: "Venerable Leo, Pope of Rome",
		nameEl: "Όσιος Λέων, Πάπας Ρώμης",
		nameId: "Js. Leo, Paus Roma",
		julianMonth: 2,
		julianDay: 18,
	},
	{
		name: "Holy Apostle Archippos",
		nameEl: "Άγιος Απόστολος Άρχιππος",
		nameId: "Rasul Kudus Arkhippos",
		julianMonth: 2,
		julianDay: 19,
	},
	{
		name: "Veneration of Leo, Bishop of Catana",
		nameEl: "Μνήμη Λέοντος, Επισκόπου Κατάνης",
		nameId: "Peringatan Js. Leo, Uskup Katana",
		julianMonth: 2,
		julianDay: 20,
	},
	{
		name: "Venerable Eustathios, Archbishop of Antioch",
		nameEl: "Όσιος Ευστάθιος, Αρχιεπίσκοπος Αντιοχείας",
		nameId: "Js. Eustathios, Uskup Agung Antiokhia",
		julianMonth: 2,
		julianDay: 21,
	},
	{
		name: "Venerable Timothy the Symbolite",
		nameEl: "Όσιος Τιμόθεος ο εν Συμβόλοις",
		nameId: "Js. Timotius sang Simbolit",
		julianMonth: 2,
		julianDay: 21,
	},
	{
		name: "Holy Hieromartyr Polycarp, Bishop of Smyrna",
		nameEl: "Άγιος Ιερομάρτυς Πολύκαρπος, Επίσκοπος Σμύρνης",
		nameId: "Hieromartir Kudus Polikarpus, Uskup Smirna",
		julianMonth: 2,
		julianDay: 23,
	},
	{
		name: "Veneration of Tarasios, Archbishop of Constantinople",
		nameEl: "Μνήμη Ταρασίου, Αρχιεπισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Tarasios, Uskup Agung Konstantinopel",
		julianMonth: 2,
		julianDay: 25,
	},
	{
		name: "Veneration of Porphyrios, Bishop of Gaza",
		nameEl: "Μνήμη Πορφυρίου, Επισκόπου Γάζης",
		nameId: "Peringatan Js. Porphyrios, Uskup Gaza",
		julianMonth: 2,
		julianDay: 26,
	},
	{
		name: "Venerable Procopius the Decapolite",
		nameEl: "Όσιος Προκόπιος ο Δεκαπολίτης",
		nameId: "Js. Prokopius sang Dekapolit",
		julianMonth: 2,
		julianDay: 27,
	},
	{
		name: "Veneration of Basil the Confessor, companion of Saint Procopius",
		nameEl: "Μνήμη Βασιλείου του Ομολογητού, συνοδοιπόρου του Αγίου Προκοπίου",
		nameId: "Peringatan Js. Basilius sang Pengaku Iman, sahabat Js. Prokopius",
		julianMonth: 2,
		julianDay: 28,
	},
	{
		name: "Venerable Cassian the Roman",
		nameEl: "Όσιος Κασσιανός ο Ρωμαίος",
		nameId: "Js. Kassianus dari Roma",
		julianMonth: 2,
		julianDay: 29,
	},

	// ─── MARCH ───────────────────────────────────
	{
		name: "Holy Hosiomartyr Eudocia",
		nameEl: "Αγία Οσιομάρτυς Ευδοκία",
		nameId: "Hosiomartir Kudus Eudokia",
		julianMonth: 3,
		julianDay: 1,
	},
	{
		name: "Holy Hieromartyr Theodotos, Bishop of Cyrene",
		nameEl: "Ιερομάρτυς Θεόδοτος, Επίσκοπος Κυρήνης",
		nameId: "Hieromartir Kudus Theodotos, Uskup Kirene",
		julianMonth: 3,
		julianDay: 2,
	},
	{
		name: "Holy Martyr Basiliskos",
		nameEl: "Άγιος Μάρτυς Βασιλίσκος",
		nameId: "Martir Kudus Basiliskos",
		julianMonth: 3,
		julianDay: 3,
	},
	{
		name: "Holy Martyr Cleonicos",
		nameEl: "Άγιος Μάρτυς Κλεόνικος",
		nameId: "Martir Kudus Kleonikos",
		julianMonth: 3,
		julianDay: 3,
	},
	{
		name: "Holy Martyr Eutropios",
		nameEl: "Άγιος Μάρτυς Ευτρόπιος",
		nameId: "Martir Kudus Eutropios",
		julianMonth: 3,
		julianDay: 3,
	},
	{
		name: "Venerable Gerasimos of Jordan",
		nameEl: "Όσιος Γεράσιμος ο Ιορδανίτης",
		nameId: "Js. Gerasimos dari Yordan",
		julianMonth: 3,
		julianDay: 4,
	},
	{
		name: "Holy Martyr Bassoi",
		nameEl: "Άγιος Μάρτυς Βασσοί",
		nameId: "Martir Kudus Bassoi",
		julianMonth: 3,
		julianDay: 6,
	},
	{
		name: "Holy Martyr Callistos",
		nameEl: "Άγιος Μάρτυς Κάλλιστος",
		nameId: "Martir Kudus Kallistos",
		julianMonth: 3,
		julianDay: 6,
	},
	{
		name: "Holy Martyr Constantine",
		nameEl: "Άγιος Μάρτυς Κωνσταντίνος",
		nameId: "Martir Kudus Konstantinus",
		julianMonth: 3,
		julianDay: 6,
	},
	{
		name: "Holy Martyr Theodore",
		nameEl: "Άγιος Μάρτυς Θεόδωρος",
		nameId: "Martir Kudus Theodorus",
		julianMonth: 3,
		julianDay: 6,
	},
	{
		name: "Holy Martyr Theophilos",
		nameEl: "Άγιος Μάρτυς Θεόφιλος",
		nameId: "Martir Kudus Theofilos",
		julianMonth: 3,
		julianDay: 6,
	},
	{
		name: "Holy Hieromartyr Agathodoros",
		nameEl: "Άγιος Ιερομάρτυς Αγαθόδωρος",
		nameId: "Hieromartir Kudus Agathodoros",
		julianMonth: 3,
		julianDay: 7,
	},
	{
		name: "Holy Hieromartyr Basil",
		nameEl: "Άγιος Ιερομάρτυς Βασίλειος",
		nameId: "Hieromartir Kudus Basilius",
		julianMonth: 3,
		julianDay: 7,
	},
	{
		name: "Holy Hieromartyr Capiton",
		nameEl: "Άγιος Ιερομάρτυς Καπίτων",
		nameId: "Hieromartir Kudus Kapiton",
		julianMonth: 3,
		julianDay: 7,
	},
	{
		name: "Holy Hieromartyr Elpidios",
		nameEl: "Άγιος Ιερομάρτυς Ελπίδιος",
		nameId: "Hieromartir Kudus Elpidios",
		julianMonth: 3,
		julianDay: 7,
	},
	{
		name: "Holy Hieromartyr Etherios",
		nameEl: "Άγιος Ιερομάρτυς Εθέριος",
		nameId: "Hieromartir Kudus Etherios",
		julianMonth: 3,
		julianDay: 7,
	},
	{
		name: "Holy Hieromartyr Eugene",
		nameEl: "Άγιος Ιερομάρτυς Ευγένιος",
		nameId: "Hieromartir Kudus Eugenius",
		julianMonth: 3,
		julianDay: 7,
	},
	{
		name: "Venerable Theophylaktos, Metropolitan of Nicomedia",
		nameEl: "Όσιος Θεοφύλακτος, Μητροπολίτης Νικομηδείας",
		nameId: "Js. Theofilaktos, Metropolitan Nikomedia",
		julianMonth: 3,
		julianDay: 8,
	},
	{
		name: "Holy Martyr Quadratus of Corinth",
		nameEl: "Άγιος Μάρτυς Κοδράτος ο εν Κορίνθω",
		nameId: "Martir Kudus Kuadratus dari Korintus",
		julianMonth: 3,
		julianDay: 10,
	},
	{
		name: "Veneration of Sophronios, Archbishop of Jerusalem",
		nameEl: "Μνήμη Σωφρονίου, Αρχιεπισκόπου Ιεροσολύμων",
		nameId: "Peringatan Js. Sophronios, Uskup Agung Yerusalem",
		julianMonth: 3,
		julianDay: 11,
	},
	{
		name: "Venerable Theophanes of Sigriana",
		nameEl: "Όσιος Θεοφάνης ο εκ Σιγριανής",
		nameId: "Js. Theofanes dari Sigriana",
		julianMonth: 3,
		julianDay: 12,
	},
	{
		name: "Venerable Benedict",
		nameEl: "Όσιος Βενέδικτος",
		nameId: "Js. Benediktus",
		julianMonth: 3,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Dionysius",
		nameEl: "Άγιος Μάρτυς Διονύσιος",
		nameId: "Martir Kudus Dionisius",
		julianMonth: 3,
		julianDay: 15,
	},
	{
		name: "Holy Martyr Paesis",
		nameEl: "Άγιος Μάρτυς Παΐσιος",
		nameId: "Martir Kudus Paesis",
		julianMonth: 3,
		julianDay: 15,
	},
	{
		name: "Holy Martyr Romylos the Subdeacon",
		nameEl: "Άγιος Μάρτυς Ρωμύλος ο Υποδιάκονος",
		nameId: "Martir Kudus Romylos sang Subdiakon",
		julianMonth: 3,
		julianDay: 15,
	},
	{
		name: "Holy Martyr Timolaos",
		nameEl: "Άγιος Μάρτυς Τιμόλαος",
		nameId: "Martir Kudus Timolaos",
		julianMonth: 3,
		julianDay: 15,
	},
	{
		name: "Holy Hieromartyr Sabinos the Egyptian",
		nameEl: "Άγιος Ιερομάρτυς Σαβίνος ο Αιγύπτιος",
		nameId: "Hieromartir Kudus Sabinos dari Mesir",
		julianMonth: 3,
		julianDay: 16,
	},
	{
		name: "Holy Martyr Alexander of Egypt",
		nameEl: "Άγιος Μάρτυς Αλέξανδρος ο εξ Αιγύπτου",
		nameId: "Martir Kudus Alexander dari Mesir",
		julianMonth: 3,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Alexander of Gaza",
		nameEl: "Άγιος Μάρτυς Αλέξανδρος ο εκ Γάζης",
		nameId: "Martir Kudus Alexander dari Gaza",
		julianMonth: 3,
		julianDay: 17,
	},
	{
		name: "Venerable Alexis the Man of God",
		nameEl: "Όσιος Αλέξιος ο Άνθρωπος του Θεού",
		nameId: "Js. Aleksis Manusia Allah",
		julianMonth: 3,
		julianDay: 17,
	},
	{
		name: "Veneration of Cyril, Archbishop of Jerusalem",
		nameEl: "Μνήμη Κυρίλλου, Αρχιεπισκόπου Ιεροσολύμων",
		nameId: "Peringatan Js. Kyrilos, Uskup Agung Yerusalem",
		julianMonth: 3,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Chrysanthos",
		nameEl: "Άγιος Μάρτυς Χρύσανθος",
		nameId: "Martir Kudus Khrisanthos",
		julianMonth: 3,
		julianDay: 19,
	},
	{
		name: "Holy Martyr Daria",
		nameEl: "Αγία Μάρτυς Δαρεία",
		nameId: "Martir Kudus Daria",
		julianMonth: 3,
		julianDay: 19,
	},
	{
		name: "Venerable James the Confessor, Bishop of Catana",
		nameEl: "Όσιος Ιάκωβος ο Ομολογητής, Επίσκοπος Κατάνης",
		nameId: "Js. Yakobus sang Pengaku Iman, Uskup Katana",
		julianMonth: 3,
		julianDay: 21,
	},
	{
		name: "Holy Hieromartyr Basil, Priest of the Church of Ancyra",
		nameEl: "Άγιος Ιερομάρτυς Βασίλειος, Πρεσβύτερος Αγκύρας",
		nameId: "Hieromartir Kudus Basilius, Imam Gereja Ankyra",
		julianMonth: 3,
		julianDay: 22,
	},
	{
		name: "Holy Hieromartyr Nikon",
		nameEl: "Άγιος Ιερομάρτυς Νίκων",
		nameId: "Hieromartir Kudus Nikon",
		julianMonth: 3,
		julianDay: 23,
	},
	{
		name: "Venerable Zacharia the Recluse",
		nameEl: "Όσιος Ζαχαρίας ο Εγκλειστός",
		nameId: "Js. Zakharia sang Petapa",
		julianMonth: 3,
		julianDay: 24,
	},
	{
		name: "Synaxis of Archangel Gabriel",
		nameEl: "Σύναξις Αρχαγγέλου Γαβριήλ",
		nameId: "Sinaxi Malaikat Agung Gabriel",
		julianMonth: 3,
		julianDay: 26,
	},
	{
		name: "Venerable Matrona of Thessalonica",
		nameEl: "Οσία Ματρώνα η Θεσσαλονίκης",
		nameId: "Js. Matrona dari Tesalonika",
		julianMonth: 3,
		julianDay: 27,
	},
	{
		name: "Venerable Hilarion the Younger",
		nameEl: "Όσιος Ιλαρίων ο Νέος",
		nameId: "Js. Hilarion Muda",
		julianMonth: 3,
		julianDay: 28,
	},
	{
		name: "Venerable Stephen the Wonderworker",
		nameEl: "Όσιος Στέφανος ο Θαυματουργός",
		nameId: "Js. Stefanus sang Pekerja Mukjizat",
		julianMonth: 3,
		julianDay: 28,
	},
	{
		name: "Holy Martyr Cyril the Deacon",
		nameEl: "Άγιος Μάρτυς Κύριλλος ο Διάκονος",
		nameId: "Martir Kudus Kyrilos sang Diakon",
		julianMonth: 3,
		julianDay: 29,
	},
	{
		name: "Venerable Mark, Bishop of Arethusa",
		nameEl: "Όσιος Μάρκος, Επίσκοπος Αρεθούσης",
		nameId: "Js. Markus, Uskup Arethusa",
		julianMonth: 3,
		julianDay: 29,
	},
	{
		name: "Venerable John Climacus",
		nameEl: "Όσιος Ιωάννης της Κλίμακος",
		nameId: "Js. Yohanes Klimakus",
		julianMonth: 3,
		julianDay: 30,
	},
	{
		name: "Veneration of Hypatios, Bishop of Gangra",
		nameEl: "Μνήμη Υπατίου, Επισκόπου Γάγγρας",
		nameId: "Peringatan Js. Hypatios, Uskup Gangra",
		julianMonth: 3,
		julianDay: 31,
	},

	// ─── APRIL ───────────────────────────────────
	{
		name: "Venerable Mary the Egyptian",
		nameEl: "Οσία Μαρία η Αιγυπτία",
		nameId: "Js. Maria dari Mesir",
		julianMonth: 4,
		julianDay: 1,
	},
	{
		name: "Veneration of Titus the Wonderworker",
		nameEl: "Μνήμη Τίτου του Θαυματουργού",
		nameId: "Peringatan Js. Titus sang Pekerja Mukjizat",
		julianMonth: 4,
		julianDay: 2,
	},
	{
		name: "Venerable Nikita, Hegumen of the monastery of Medicius",
		nameEl: "Όσιος Νικήτας, Ηγούμενος Μονής Μηδικίου",
		nameId: "Js. Nikita, Hegumen Biara Medicius",
		julianMonth: 4,
		julianDay: 3,
	},
	{
		name: "Venerable Nikon the Preacher of Repentance",
		nameEl: "Όσιος Νίκων ο Μετανοείτε",
		nameId: "Js. Nikon sang Pengkhotbah Pertobatan",
		julianMonth: 4,
		julianDay: 3,
	},
	{
		name: "Holy Martyr Agathopodos",
		nameEl: "Άγιος Μάρτυς Αγαθόπους",
		nameId: "Martir Kudus Agathopodos",
		julianMonth: 4,
		julianDay: 4,
	},
	{
		name: "Venerable George of Maleum",
		nameEl: "Όσιος Γεώργιος ο Μαλεΐνος",
		nameId: "Js. Georgius dari Maleum",
		julianMonth: 4,
		julianDay: 4,
	},
	{
		name: "Venerable George the Chozebite",
		nameEl: "Όσιος Γεώργιος ο Χοζεβίτης",
		nameId: "Js. Georgius sang Khozevit",
		julianMonth: 4,
		julianDay: 4,
	},
	{
		name: "Venerable Joseph the Hymnographer",
		nameEl: "Όσιος Ιωσήφ ο Υμνογράφος",
		nameId: "Js. Yusuf sang Pembuat Himne",
		julianMonth: 4,
		julianDay: 4,
	},
	{
		name: "Holy Martyr Theodulos",
		nameEl: "Άγιος Μάρτυς Θεόδουλος",
		nameId: "Martir Kudus Theodulos",
		julianMonth: 4,
		julianDay: 4,
	},
	{
		name: "Holy Martyr Claudius",
		nameEl: "Άγιος Μάρτυς Κλαύδιος",
		nameId: "Martir Kudus Klaudius",
		julianMonth: 4,
		julianDay: 5,
	},
	{
		name: "Holy Martyr Diodorus",
		nameEl: "Άγιος Μάρτυς Διόδωρος",
		nameId: "Martir Kudus Diodorus",
		julianMonth: 4,
		julianDay: 5,
	},
	{
		name: "Holy Martyr Nicephoros",
		nameEl: "Άγιος Μάρτυς Νικηφόρος",
		nameId: "Martir Kudus Nikephoros",
		julianMonth: 4,
		julianDay: 5,
	},
	{
		name: "Holy Martyr Pappias",
		nameEl: "Άγιος Μάρτυς Παππίας",
		nameId: "Martir Kudus Pappias",
		julianMonth: 4,
		julianDay: 5,
	},
	{
		name: "Holy Martyr Serapion",
		nameEl: "Άγιος Μάρτυς Σεραπίων",
		nameId: "Martir Kudus Serapion",
		julianMonth: 4,
		julianDay: 5,
	},
	{
		name: "Veneration of Eutychios, Archbishop of Constantinople",
		nameEl: "Μνήμη Ευτυχίου, Αρχιεπισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Eutykhios, Uskup Agung Konstantinopel",
		julianMonth: 4,
		julianDay: 6,
	},
	{
		name: "Veneration of George, Bishop of Melitene",
		nameEl: "Μνήμη Γεωργίου, Επισκόπου Μελιτηνής",
		nameId: "Peringatan Js. Georgius, Uskup Melitene",
		julianMonth: 4,
		julianDay: 7,
	},
	{
		name: "Holy Martyr Kalliopios",
		nameEl: "Άγιος Μάρτυς Καλλιόπιος",
		nameId: "Martir Kudus Kalliopios",
		julianMonth: 4,
		julianDay: 7,
	},
	{
		name: "Holy Apostle Agabos",
		nameEl: "Άγιος Απόστολος Άγαβος",
		nameId: "Rasul Kudus Agabos",
		julianMonth: 4,
		julianDay: 8,
	},
	{
		name: "Holy Apostle Asyncritos",
		nameEl: "Άγιος Απόστολος Ασύγκριτος",
		nameId: "Rasul Kudus Asyncritos",
		julianMonth: 4,
		julianDay: 8,
	},
	{
		name: "Holy Apostle Hermes",
		nameEl: "Άγιος Απόστολος Ερμής",
		nameId: "Rasul Kudus Hermes",
		julianMonth: 4,
		julianDay: 8,
	},
	{
		name: "Holy Apostle Herodion",
		nameEl: "Άγιος Απόστολος Ηρωδίων",
		nameId: "Rasul Kudus Herodion",
		julianMonth: 4,
		julianDay: 8,
	},
	{
		name: "Holy Apostle Phlegon",
		nameEl: "Άγιος Απόστολος Φλέγων",
		nameId: "Rasul Kudus Phlegon",
		julianMonth: 4,
		julianDay: 8,
	},
	{
		name: "Holy Apostle Rufus",
		nameEl: "Άγιος Απόστολος Ρούφος",
		nameId: "Rasul Kudus Rufus",
		julianMonth: 4,
		julianDay: 8,
	},
	{
		name: "Holy Martyr Eupsychios",
		nameEl: "Άγιος Μάρτυς Ευψύχιος",
		nameId: "Martir Kudus Eupsykhios",
		julianMonth: 4,
		julianDay: 9,
	},
	{
		name: "Holy Martyr Afrikanos",
		nameEl: "Άγιος Μάρτυς Αφρικανός",
		nameId: "Martir Kudus Afrikanos",
		julianMonth: 4,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Makarios",
		nameEl: "Άγιος Μάρτυς Μακάριος",
		nameId: "Martir Kudus Makarios",
		julianMonth: 4,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Maximos",
		nameEl: "Άγιος Μάρτυς Μάξιμος",
		nameId: "Martir Kudus Maximos",
		julianMonth: 4,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Pompeius",
		nameEl: "Άγιος Μάρτυς Πομπήιος",
		nameId: "Martir Kudus Pompeius",
		julianMonth: 4,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Terentios",
		nameEl: "Άγιος Μάρτυς Τερέντιος",
		nameId: "Martir Kudus Terentios",
		julianMonth: 4,
		julianDay: 10,
	},
	{
		name: "Veneration of Basil the Confessor, Bishop of Parios",
		nameEl: "Μνήμη Βασιλείου του Ομολογητού, Επισκόπου Πάρου",
		nameId: "Peringatan Js. Basilius sang Pengaku Iman, Uskup Parios",
		julianMonth: 4,
		julianDay: 12,
	},
	{
		name: "Veneration of Martin, Pope of Rome",
		nameEl: "Μνήμη Μαρτίνου, Πάπα Ρώμης",
		nameId: "Peringatan Js. Martinus, Paus Roma",
		julianMonth: 4,
		julianDay: 13,
	},
	{
		name: "Holy Apostle Aristarchos",
		nameEl: "Άγιος Απόστολος Αρίσταρχος",
		nameId: "Rasul Kudus Aristarkhos",
		julianMonth: 4,
		julianDay: 14,
	},
	{
		name: "Holy Apostle Pudens",
		nameEl: "Άγιος Απόστολος Πούδης",
		nameId: "Rasul Kudus Pudens",
		julianMonth: 4,
		julianDay: 14,
	},
	{
		name: "Holy Apostle Trophimos",
		nameEl: "Άγιος Απόστολος Τρόφιμος",
		nameId: "Rasul Kudus Trofimos",
		julianMonth: 4,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Crescens",
		nameEl: "Άγιος Μάρτυς Κρήσκης",
		nameId: "Martir Kudus Crescens",
		julianMonth: 4,
		julianDay: 15,
	},
	{
		name: "Holy Martyr Chionia",
		nameEl: "Αγία Μάρτυς Χιονία",
		nameId: "Martir Kudus Khionia",
		julianMonth: 4,
		julianDay: 16,
	},
	{
		name: "Holy Martyr Irene",
		nameEl: "Αγία Μάρτυς Ειρήνη",
		nameId: "Martir Kudus Irene",
		julianMonth: 4,
		julianDay: 16,
	},
	{
		name: "Venerable Akakios, Bishop of Melitene",
		nameEl: "Όσιος Ακάκιος, Επίσκοπος Μελιτηνής",
		nameId: "Js. Akakios, Uskup Melitene",
		julianMonth: 4,
		julianDay: 17,
	},
	{
		name: "Holy Hieromartyr Simeon the Persian",
		nameEl: "Άγιος Ιερομάρτυς Συμεών ο Πέρσης",
		nameId: "Hieromartir Kudus Simeon dari Persia",
		julianMonth: 4,
		julianDay: 17,
	},
	{
		name: "Venerable John, Disciple of Saint Gregory the Decapolite",
		nameEl: "Όσιος Ιωάννης, Μαθητής του Αγίου Γρηγορίου του Δεκαπολίτου",
		nameId: "Js. Yohanes, Murid Js. Gregorius sang Dekapolit",
		julianMonth: 4,
		julianDay: 18,
	},
	{
		name: "Venerable John of the Old Laura",
		nameEl: "Όσιος Ιωάννης της Παλαιάς Λαύρας",
		nameId: "Js. Yohanes dari Laura Lama",
		julianMonth: 4,
		julianDay: 19,
	},
	{
		name: "Holy Hieromartyr Paphnutios",
		nameEl: "Άγιος Ιερομάρτυς Παφνούτιος",
		nameId: "Hieromartir Kudus Paphnutios",
		julianMonth: 4,
		julianDay: 19,
	},
	{
		name: "Veneration of Theodore the Hairy",
		nameEl: "Μνήμη Θεοδώρου του Τριχινά",
		nameId: "Peringatan Js. Theodorus sang Berbulu",
		julianMonth: 4,
		julianDay: 20,
	},
	{
		name: "Holy Hieromartyr Januarios",
		nameEl: "Άγιος Ιερομάρτυς Ιανουάριος",
		nameId: "Hieromartir Kudus Januarios",
		julianMonth: 4,
		julianDay: 21,
	},
	{
		name: "Holy Martyr Theodore of Pergia",
		nameEl: "Άγιος Μάρτυς Θεόδωρος ο εκ Πέργης",
		nameId: "Martir Kudus Theodorus dari Pergia",
		julianMonth: 4,
		julianDay: 21,
	},
	{
		name: "Venerable Theodore Sykeotes",
		nameEl: "Όσιος Θεόδωρος ο Συκεώτης",
		nameId: "Js. Theodorus Sikeot",
		julianMonth: 4,
		julianDay: 22,
	},
	{
		name: "Holy Great Martyr George the Triumphant",
		nameEl: "Άγιος Μεγαλομάρτυς Γεώργιος ο Τροπαιοφόρος",
		nameId: "Martir Agung Kudus Georgius sang Pembawa Kemenangan",
		julianMonth: 4,
		julianDay: 23,
	},
	{
		name: "Venerable Elizabeth",
		nameEl: "Οσία Ελισάβετ",
		nameId: "Js. Elisabet",
		julianMonth: 4,
		julianDay: 24,
	},
	{
		name: "Holy Martyr Sabbas the Goth",
		nameEl: "Άγιος Μάρτυς Σάββας ο Γότθος",
		nameId: "Martir Kudus Sabbas sang Goth",
		julianMonth: 4,
		julianDay: 24,
	},
	{
		name: "Holy Apostle and Evangelist Mark",
		nameEl: "Άγιος Απόστολος και Ευαγγελιστής Μάρκος",
		nameId: "Rasul dan Penginjil Kudus Markus",
		julianMonth: 4,
		julianDay: 25,
	},
	{
		name: "Holy Hieromartyr Simeon, a relative of the Lord",
		nameEl: "Άγιος Ιερομάρτυς Συμεών ο Συγγενής του Κυρίου",
		nameId: "Hieromartir Kudus Simeon, kerabat Tuhan",
		julianMonth: 4,
		julianDay: 27,
	},
	{
		name: "Holy Martyr Dadas",
		nameEl: "Άγιος Μάρτυς Δαδάς",
		nameId: "Martir Kudus Dadas",
		julianMonth: 4,
		julianDay: 28,
	},
	{
		name: "Holy Apostle Jason",
		nameEl: "Άγιος Απόστολος Ιάσων",
		nameId: "Rasul Kudus Yason",
		julianMonth: 4,
		julianDay: 28,
	},
	{
		name: "Holy Martyr Maximos",
		nameEl: "Άγιος Μάρτυς Μάξιμος",
		nameId: "Martir Kudus Maximos",
		julianMonth: 4,
		julianDay: 28,
	},
	{
		name: "Holy Martyr Quintillian",
		nameEl: "Άγιος Μάρτυς Κυντιλλιανός",
		nameId: "Martir Kudus Quintillian",
		julianMonth: 4,
		julianDay: 28,
	},
	{
		name: "Holy Apostle Sosipater",
		nameEl: "Άγιος Απόστολος Σωσίπατρος",
		nameId: "Rasul Kudus Sosipater",
		julianMonth: 4,
		julianDay: 28,
	},
	{
		name: "Holy Martyr Antipater",
		nameEl: "Άγιος Μάρτυς Αντίπατρος",
		nameId: "Martir Kudus Antipater",
		julianMonth: 4,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Artemas",
		nameEl: "Άγιος Μάρτυς Αρτεμάς",
		nameId: "Martir Kudus Artemas",
		julianMonth: 4,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Magnus",
		nameEl: "Άγιος Μάρτυς Μάγνος",
		nameId: "Martir Kudus Magnus",
		julianMonth: 4,
		julianDay: 29,
	},
	{
		name: "Venerable Memnon",
		nameEl: "Όσιος Μέμνων",
		nameId: "Js. Memnon",
		julianMonth: 4,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Philemon",
		nameEl: "Άγιος Μάρτυς Φιλήμων",
		nameId: "Martir Kudus Filemon",
		julianMonth: 4,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Rufus",
		nameEl: "Άγιος Μάρτυς Ρούφος",
		nameId: "Martir Kudus Rufus",
		julianMonth: 4,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Thaumasius",
		nameEl: "Άγιος Μάρτυς Θαυμάσιος",
		nameId: "Martir Kudus Thaumasios",
		julianMonth: 4,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Theodotos",
		nameEl: "Άγιος Μάρτυς Θεόδοτος",
		nameId: "Martir Kudus Theodotos",
		julianMonth: 4,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Theognis",
		nameEl: "Άγιος Μάρτυς Θεόγνις",
		nameId: "Martir Kudus Theognis",
		julianMonth: 4,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Theosticus",
		nameEl: "Άγιος Μάρτυς Θεόστικτος",
		nameId: "Martir Kudus Theostiktos",
		julianMonth: 4,
		julianDay: 29,
	},

	// ─── MAY ───────────────────────────────────
	{
		name: "Prophet Jeremia",
		nameEl: "Προφήτης Ιερεμίας",
		nameId: "Nabi Yeremia",
		julianMonth: 5,
		julianDay: 1,
	},
	{
		name: "Translation of the Relics of Athanasius the Great",
		nameEl: "Ανακομιδή Λειψάνων Αθανασίου του Μεγάλου",
		nameId: "Pemindahan Relikui Js. Athanasius Agung",
		julianMonth: 5,
		julianDay: 2,
	},
	{
		name: "Holy Martyr Maura",
		nameEl: "Αγία Μάρτυς Μαύρα",
		nameId: "Martir Kudus Maura",
		julianMonth: 5,
		julianDay: 3,
	},
	{
		name: "Holy Martyr Timothy",
		nameEl: "Άγιος Μάρτυς Τιμόθεος",
		nameId: "Martir Kudus Timotius",
		julianMonth: 5,
		julianDay: 3,
	},
	{
		name: "Holy Martyr Pelagia",
		nameEl: "Αγία Μάρτυς Πελαγία",
		nameId: "Martir Kudus Pelagia",
		julianMonth: 5,
		julianDay: 4,
	},
	{
		name: "Holy Martyr Irene",
		nameEl: "Αγία Μάρτυς Ειρήνη",
		nameId: "Martir Kudus Irene",
		julianMonth: 5,
		julianDay: 5,
	},
	{
		name: "Veneration of Righteous Job the Long-suffering",
		nameEl: "Μνήμη Δικαίου Ιώβ του Πολυάθλου",
		nameId: "Peringatan Js. Ayub yang Banyak Menderita",
		julianMonth: 5,
		julianDay: 6,
	},
	{
		name: "Veneration of Arsenios the Great",
		nameEl: "Μνήμη Αρσενίου του Μεγάλου",
		nameId: "Peringatan Js. Arsenios Agung",
		julianMonth: 5,
		julianDay: 8,
	},
	{
		name: "Holy Martyr Christopher",
		nameEl: "Άγιος Μάρτυς Χριστόφορος",
		nameId: "Martir Kudus Kristoforus",
		julianMonth: 5,
		julianDay: 9,
	},
	{
		name: "Prophet Isaias",
		nameEl: "Προφήτης Ησαΐας",
		nameId: "Nabi Yesaya",
		julianMonth: 5,
		julianDay: 9,
	},
	{
		name: "Holy Apostle Simeon the Zealot",
		nameEl: "Άγιος Απόστολος Σίμων ο Ζηλωτής",
		nameId: "Rasul Kudus Simeon sang Zelot",
		julianMonth: 5,
		julianDay: 10,
	},
	{
		name: "Holy Equal-to-the-Apostles Cyril, Apostle of the Slavs",
		nameEl: "Άγιος Ισαπόστολος Κύριλλος, Απόστολος των Σλάβων",
		nameId: "Kudus Setara-Rasul Kyrilos, Rasul Bangsa Slavia",
		julianMonth: 5,
		julianDay: 11,
	},
	{
		name: "Holy Equal-to-the-Apostles Methodius, Apostle of the Slavs",
		nameEl: "Άγιος Ισαπόστολος Μεθόδιος, Απόστολος των Σλάβων",
		nameId: "Kudus Setara-Rasul Methodius, Rasul Bangsa Slavia",
		julianMonth: 5,
		julianDay: 11,
	},
	{
		name: "Holy Hieromartyr Mokios",
		nameEl: "Άγιος Ιερομάρτυς Μώκιος",
		nameId: "Hieromartir Kudus Mokios",
		julianMonth: 5,
		julianDay: 11,
	},
	{
		name: "Veneration of Epiphanios, Bishop of Cyprus",
		nameEl: "Μνήμη Επιφανίου, Επισκόπου Κύπρου",
		nameId: "Peringatan Js. Epiphanios, Uskup Siprus",
		julianMonth: 5,
		julianDay: 12,
	},
	{
		name: "Veneration of Germanus, Archbishop of Constantinople",
		nameEl: "Μνήμη Γερμανού, Αρχιεπισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Germanus, Uskup Agung Konstantinopel",
		julianMonth: 5,
		julianDay: 12,
	},
	{
		name: "Holy Martyr Glyceria",
		nameEl: "Αγία Μάρτυς Γλυκερία",
		nameId: "Martir Kudus Glykeria",
		julianMonth: 5,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Isidore of Chios",
		nameEl: "Άγιος Μάρτυς Ισίδωρος ο εν Χίω",
		nameId: "Martir Kudus Isidorus dari Khios",
		julianMonth: 5,
		julianDay: 14,
	},
	{
		name: "Venerable Achillios, Archbishop of Larissa",
		nameEl: "Όσιος Αχίλλιος, Αρχιεπίσκοπος Λαρίσης",
		nameId: "Js. Akhillios, Uskup Agung Larissa",
		julianMonth: 5,
		julianDay: 15,
	},
	{
		name: "Venerable Pachomios the Great",
		nameEl: "Όσιος Παχώμιος ο Μέγας",
		nameId: "Js. Pakhomius Agung",
		julianMonth: 5,
		julianDay: 15,
	},
	{
		name: "Venerable Theodore the Sanctified",
		nameEl: "Όσιος Θεόδωρος ο Ηγιασμένος",
		nameId: "Js. Theodorus yang Dikuduskan",
		julianMonth: 5,
		julianDay: 16,
	},
	{
		name: "Holy Apostle Andronicos",
		nameEl: "Άγιος Απόστολος Ανδρόνικος",
		nameId: "Rasul Kudus Andronikos",
		julianMonth: 5,
		julianDay: 17,
	},
	{
		name: "Holy Apostle Junias",
		nameEl: "Άγιος Απόστολος Ιουνίας",
		nameId: "Rasul Kudus Junias",
		julianMonth: 5,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Andrew",
		nameEl: "Άγιος Μάρτυς Ανδρέας",
		nameId: "Martir Kudus Andreas",
		julianMonth: 5,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Benedimos",
		nameEl: "Άγιος Μάρτυς Βενέδιμος",
		nameId: "Martir Kudus Benedimos",
		julianMonth: 5,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Christina",
		nameEl: "Αγία Μάρτυς Χριστίνα",
		nameId: "Martir Kudus Kristina",
		julianMonth: 5,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Dionysia",
		nameEl: "Αγία Μάρτυς Διονυσία",
		nameId: "Martir Kudus Dionysia",
		julianMonth: 5,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Heraclius",
		nameEl: "Άγιος Μάρτυς Ηράκλειος",
		nameId: "Martir Kudus Heraclius",
		julianMonth: 5,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Paul",
		nameEl: "Άγιος Μάρτυς Παύλος",
		nameId: "Martir Kudus Paulus",
		julianMonth: 5,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Paulinos",
		nameEl: "Άγιος Μάρτυς Παυλίνος",
		nameId: "Martir Kudus Paulinos",
		julianMonth: 5,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Peter",
		nameEl: "Άγιος Μάρτυς Πέτρος",
		nameId: "Martir Kudus Petrus",
		julianMonth: 5,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Akakios",
		nameEl: "Άγιος Μάρτυς Ακάκιος",
		nameId: "Martir Kudus Akakios",
		julianMonth: 5,
		julianDay: 19,
	},
	{
		name: "Holy Martyr Menander",
		nameEl: "Άγιος Μάρτυς Μένανδρος",
		nameId: "Martir Kudus Menander",
		julianMonth: 5,
		julianDay: 19,
	},
	{
		name: "Holy Martyr Patricios",
		nameEl: "Άγιος Μάρτυς Πατρίκιος",
		nameId: "Martir Kudus Patrikios",
		julianMonth: 5,
		julianDay: 19,
	},
	{
		name: "Holy Martyr Polyenos",
		nameEl: "Άγιος Μάρτυς Πολύαινος",
		nameId: "Martir Kudus Polyenos",
		julianMonth: 5,
		julianDay: 19,
	},
	{
		name: "Holy Martyr Thallelaios",
		nameEl: "Άγιος Μάρτυς Θαλλέλαιος",
		nameId: "Martir Kudus Thallelaios",
		julianMonth: 5,
		julianDay: 20,
	},
	{
		name: "Holy Equal-to-the-Apostles Emperor Constantine the Great",
		nameEl: "Άγιος Ισαπόστολος Κωνσταντίνος ο Μέγας",
		nameId: "Kudus Setara-Rasul Kaisar Konstantinus Agung",
		julianMonth: 5,
		julianDay: 21,
	},
	{
		name: "Holy Equal-to-the-Apostles Empress Helen",
		nameEl: "Αγία Ισαπόστολος Ελένη",
		nameId: "Kudus Setara-Rasul Permaisuri Helena",
		julianMonth: 5,
		julianDay: 21,
	},
	{
		name: "Holy Martyr Basiliskos",
		nameEl: "Άγιος Μάρτυς Βασιλίσκος",
		nameId: "Martir Kudus Basiliskos",
		julianMonth: 5,
		julianDay: 22,
	},
	{
		name: "Venerable Michael, Metropolitan of Synnada",
		nameEl: "Όσιος Μιχαήλ, Μητροπολίτης Συννάδων",
		nameId: "Js. Mikhael, Metropolitan Synnada",
		julianMonth: 5,
		julianDay: 23,
	},
	{
		name: "Venerable Simeon of the Wonderful Mountain",
		nameEl: "Όσιος Συμεών ο Θαυμαστορείτης",
		nameId: "Js. Simeon dari Gunung Ajaib",
		julianMonth: 5,
		julianDay: 24,
	},
	{
		name: "Holy Apostle Carpos",
		nameEl: "Άγιος Απόστολος Κάρπος",
		nameId: "Rasul Kudus Karpos",
		julianMonth: 5,
		julianDay: 26,
	},
	{
		name: "Holy Hieromartyr Helladios",
		nameEl: "Άγιος Ιερομάρτυς Ελλάδιος",
		nameId: "Hieromartir Kudus Helladios",
		julianMonth: 5,
		julianDay: 27,
	},
	{
		name: "Holy Hieromartyr Eutyches, Bishop of Melitene",
		nameEl: "Άγιος Ιερομάρτυς Ευτυχής, Επίσκοπος Μελιτηνής",
		nameId: "Hieromartir Kudus Eutyches, Uskup Melitene",
		julianMonth: 5,
		julianDay: 28,
	},
	{
		name: "Holy Hosiomartyr Theodosia",
		nameEl: "Οσιομάρτυς Θεοδοσία",
		nameId: "Osiomartir Kudus Theodosia",
		julianMonth: 5,
		julianDay: 29,
	},
	{
		name: "Venerable Isaac, Hegumen of the Monastery of Dalmaton",
		nameEl: "Όσιος Ισαάκ, Ηγούμενος Μονής Δαλμάτου",
		nameId: "Js. Ishak, Hegumen Biara Dalmaton",
		julianMonth: 5,
		julianDay: 30,
	},
	{
		name: "Holy Martyr Hermios",
		nameEl: "Άγιος Μάρτυς Ερμείος",
		nameId: "Martir Kudus Hermios",
		julianMonth: 5,
		julianDay: 31,
	},

	// ─── JUNE ───────────────────────────────────
	{
		name: "Holy Martyr Chariton",
		nameEl: "Άγιος Μάρτυς Χαρίτων",
		nameId: "Martir Kudus Khariton",
		julianMonth: 6,
		julianDay: 1,
	},
	{
		name: "Holy Martyr Charitos",
		nameEl: "Άγιος Μάρτυς Χαρίτος",
		nameId: "Martir Kudus Kharitos",
		julianMonth: 6,
		julianDay: 1,
	},
	{
		name: "Holy Martyr Evelpistos",
		nameEl: "Άγιος Μάρτυς Ευέλπιστος",
		nameId: "Martir Kudus Evelpistos",
		julianMonth: 6,
		julianDay: 1,
	},
	{
		name: "Holy Martyr Justin the Philosopher",
		nameEl: "Άγιος Μάρτυς Ιουστίνος ο Φιλόσοφος",
		nameId: "Martir Kudus Justinus sang Filsuf",
		julianMonth: 6,
		julianDay: 1,
	},
	{
		name: "Holy Martyr Liberian",
		nameEl: "Άγιος Μάρτυς Λιβεριανός",
		nameId: "Martir Kudus Liberian",
		julianMonth: 6,
		julianDay: 1,
	},
	{
		name: "Holy Martyr Peon",
		nameEl: "Άγιος Μάρτυς Πέων",
		nameId: "Martir Kudus Peon",
		julianMonth: 6,
		julianDay: 1,
	},
	{
		name: "Veneration of Nicephoros the Confessor, Archbishop of Constantinople",
		nameEl: "Μνήμη Νικηφόρου του Ομολογητού, Αρχιεπισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Nikephoros sang Pengaku Iman, Uskup Agung Konstantinopel",
		julianMonth: 6,
		julianDay: 2,
	},
	{
		name: "Holy Martyr Lucillian",
		nameEl: "Άγιος Μάρτυς Λουκιλλιανός",
		nameId: "Martir Kudus Lucillian",
		julianMonth: 6,
		julianDay: 3,
	},
	{
		name: "Veneration of Metrophanes, Bishop of Constantinople",
		nameEl: "Μνήμη Μητροφάνους, Επισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Metrophanes, Uskup Konstantinopel",
		julianMonth: 6,
		julianDay: 4,
	},
	{
		name: "Holy Hieromartyr Dorotheos, Bishop of Tyre",
		nameEl: "Άγιος Ιερομάρτυς Δωρόθεος, Επίσκοπος Τύρου",
		nameId: "Hieromartir Kudus Dorotheos, Uskup Tirus",
		julianMonth: 6,
		julianDay: 5,
	},
	{
		name: "Venerable Bessarion the Wonderworker",
		nameEl: "Όσιος Βησσαρίων ο Θαυματουργός",
		nameId: "Js. Bessarion sang Pembuat Mukjizat",
		julianMonth: 6,
		julianDay: 6,
	},
	{
		name: "Venerable Hilarion the Younger, Hegumen of the Monastery of Dalmaton",
		nameEl: "Όσιος Ιλαρίων ο Νέος, Ηγούμενος Μονής Δαλμάτου",
		nameId: "Js. Hilarion Muda, Hegumen Biara Dalmaton",
		julianMonth: 6,
		julianDay: 6,
	},
	{
		name: "Holy Hieromartyr Theodotos, Bishop of Ancyra",
		nameEl: "Ιερομάρτυς Θεόδοτος, Επίσκοπος Αγκύρας",
		nameId: "Hieromartir Kudus Theodotos, Uskup Ankira",
		julianMonth: 6,
		julianDay: 7,
	},
	{
		name: "Holy Martyr Alexander",
		nameEl: "Άγιος Μάρτυς Αλέξανδρος",
		nameId: "Martir Kudus Alexander",
		julianMonth: 6,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Antonina",
		nameEl: "Αγία Μάρτυς Αντωνίνα",
		nameId: "Martir Kudus Antonina",
		julianMonth: 6,
		julianDay: 10,
	},
	{
		name: "Holy Hieromartyr Timothy, Archbishop of Brusa",
		nameEl: "Ιερομάρτυς Τιμόθεος, Αρχιεπίσκοπος Προύσης",
		nameId: "Hieromartir Kudus Timotius, Uskup Agung Brusa",
		julianMonth: 6,
		julianDay: 10,
	},
	{
		name: "Holy Apostle Barnabas",
		nameEl: "Άγιος Απόστολος Βαρνάβας",
		nameId: "Rasul Kudus Barnabas",
		julianMonth: 6,
		julianDay: 11,
	},
	{
		name: "Holy Apostle Bartholomew",
		nameEl: "Άγιος Απόστολος Βαρθολομαίος",
		nameId: "Rasul Kudus Bartolomeus",
		julianMonth: 6,
		julianDay: 11,
	},
	{
		name: "Venerable Onuphrius",
		nameEl: "Όσιος Ονούφριος",
		nameId: "Js. Onuphrius",
		julianMonth: 6,
		julianDay: 12,
	},
	{
		name: "Venerable Peter of Mount Athos",
		nameEl: "Όσιος Πέτρος ο εν Άθω",
		nameId: "Js. Petrus dari Gunung Athos",
		julianMonth: 6,
		julianDay: 12,
	},
	{
		name: "Holy Martyr Aquilina",
		nameEl: "Αγία Μάρτυς Ακυλίνα",
		nameId: "Martir Kudus Akuilina",
		julianMonth: 6,
		julianDay: 13,
	},
	{
		name: "Veneration of Triphyllios, Bishop of Leucosia",
		nameEl: "Μνήμη Τριφυλλίου, Επισκόπου Λευκωσίας",
		nameId: "Peringatan Js. Trifillios, Uskup Leukosía",
		julianMonth: 6,
		julianDay: 13,
	},
	{
		name: "Prophet Elisae",
		nameEl: "Προφήτης Ελισαίος",
		nameId: "Nabi Elisa",
		julianMonth: 6,
		julianDay: 14,
	},
	{
		name: "Veneration of Methodius the Confessor, Archbishop of Constantinople",
		nameEl: "Μνήμη Μεθοδίου του Ομολογητού, Αρχιεπισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Methodius sang Pengaku Iman, Uskup Agung Konstantinopel",
		julianMonth: 6,
		julianDay: 14,
	},
	{
		name: "Veneration of Tychon, Bishop of Amathus",
		nameEl: "Μνήμη Τύχωνος, Επισκόπου Αμαθούντος",
		nameId: "Peringatan Js. Tikhon, Uskup Amathus",
		julianMonth: 6,
		julianDay: 16,
	},
	{
		name: "Holy Martyr Ismael",
		nameEl: "Άγιος Μάρτυς Ισμαήλ",
		nameId: "Martir Kudus Ismael",
		julianMonth: 6,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Manuel",
		nameEl: "Άγιος Μάρτυς Μανουήλ",
		nameId: "Martir Kudus Manuel",
		julianMonth: 6,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Sabel",
		nameEl: "Άγιος Μάρτυς Σαβέλ",
		nameId: "Martir Kudus Sabel",
		julianMonth: 6,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Leontios",
		nameEl: "Άγιος Μάρτυς Λεόντιος",
		nameId: "Martir Kudus Leontios",
		julianMonth: 6,
		julianDay: 18,
	},
	{
		name: "Holy Apostle Jude",
		nameEl: "Άγιος Απόστολος Ιούδας",
		nameId: "Rasul Kudus Yudas",
		julianMonth: 6,
		julianDay: 19,
	},
	{
		name: "Holy Apostle Thaddeus",
		nameEl: "Άγιος Απόστολος Θαδδαίος",
		nameId: "Rasul Kudus Tadeus",
		julianMonth: 6,
		julianDay: 19,
	},
	{
		name: "Holy Hieromartyr Methodius, Bishop of Olympus",
		nameEl: "Άγιος Ιερομάρτυς Μεθόδιος, Επίσκοπος Ολύμπου",
		nameId: "Hieromartir Kudus Methodius, Uskup Olympus",
		julianMonth: 6,
		julianDay: 20,
	},
	{
		name: "Holy Martyr Julian of Tarsus",
		nameEl: "Άγιος Μάρτυς Ιουλιανός ο εκ Ταρσού",
		nameId: "Martir Kudus Julian dari Tarsus",
		julianMonth: 6,
		julianDay: 21,
	},
	{
		name: "Holy Hieromartyr Eusebius of Samosata",
		nameEl: "Άγιος Ιερομάρτυς Ευσέβιος Σαμοσάτων",
		nameId: "Hieromartir Kudus Eusebius dari Samosata",
		julianMonth: 6,
		julianDay: 22,
	},
	{
		name: "Holy Martyr Agrippina",
		nameEl: "Αγία Μάρτυς Αγριππίνα",
		nameId: "Martir Kudus Agrippina",
		julianMonth: 6,
		julianDay: 23,
	},
	{
		name: "Holy Martyr Febronia",
		nameEl: "Αγία Μάρτυς Φεβρωνία",
		nameId: "Martir Kudus Febronia",
		julianMonth: 6,
		julianDay: 25,
	},
	{
		name: "Venerable Samson the Hospitable",
		nameEl: "Όσιος Σαμψών ο Ξενοδόχος",
		nameId: "Js. Samson sang Penjamu",
		julianMonth: 6,
		julianDay: 27,
	},
	{
		name: "Holy Unmercenary John",
		nameEl: "Άγιος Ανάργυρος Ιωάννης",
		nameId: "Kudus Tanpa Bayaran Yohanes",
		julianMonth: 6,
		julianDay: 28,
	},
	{
		name: "Holy Glorious and All-laudable Apostle Paul",
		nameEl: "Άγιος Ένδοξος και Πανεύφημος Απόστολος Παύλος",
		nameId: "Rasul Kudus yang Mulia dan Terpuji Paulus",
		julianMonth: 6,
		julianDay: 29,
	},
	{
		name: "Holy Glorious and All-laudable Apostle Peter",
		nameEl: "Άγιος Ένδοξος και Πανεύφημος Απόστολος Πέτρος",
		nameId: "Rasul Kudus yang Mulia dan Terpuji Petrus",
		julianMonth: 6,
		julianDay: 29,
	},

	// ─── JULY ───────────────────────────────────
	{
		name: "Holy Unmercenary Cosmas",
		nameEl: "Άγιος Ανάργυρος Κοσμάς",
		nameId: "Kudus Tanpa Bayaran Kosmas",
		julianMonth: 7,
		julianDay: 1,
	},
	{
		name: "Holy Unmercenary Damian",
		nameEl: "Άγιος Ανάργυρος Δαμιανός",
		nameId: "Kudus Tanpa Bayaran Damian",
		julianMonth: 7,
		julianDay: 1,
	},
	{
		name: "Veneration of Anatolios, Archbishop of Constantinople",
		nameEl: "Μνήμη Ανατολίου, Αρχιεπισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Anatolios, Uskup Agung Konstantinopel",
		julianMonth: 7,
		julianDay: 3,
	},
	{
		name: "Holy Martyr Hyacinthos",
		nameEl: "Άγιος Μάρτυς Υάκινθος",
		nameId: "Martir Kudus Hyacinthos",
		julianMonth: 7,
		julianDay: 3,
	},
	{
		name: "Veneration of Andrew of Crete, the Jerusalemite",
		nameEl: "Μνήμη Ανδρέου Κρήτης, του Ιεροσολυμίτου",
		nameId: "Peringatan Js. Andreas dari Kreta, sang Yerusalemin",
		julianMonth: 7,
		julianDay: 4,
	},
	{
		name: "Venerable Athanasius of Mount Athos",
		nameEl: "Όσιος Αθανάσιος ο εν Άθω",
		nameId: "Js. Athanasius dari Gunung Athos",
		julianMonth: 7,
		julianDay: 5,
	},
	{
		name: "Venerable Lampadios the Wonderworker",
		nameEl: "Όσιος Λαμπάδιος ο Θαυματουργός",
		nameId: "Js. Lampadios sang Pembuat Mukjizat",
		julianMonth: 7,
		julianDay: 5,
	},
	{
		name: "Veneration of Righteous Martha, Mother of Saint Simeon of the Wonderful Mountain",
		nameEl: "Μνήμη Δικαίας Μάρθας, Μητρός Αγίου Συμεών του Θαυμαστορείτου",
		nameId: "Peringatan Js. Martha, Ibu Js. Simeon dari Gunung Ajaib",
		julianMonth: 7,
		julianDay: 5,
	},
	{
		name: "Venerable Sisoes the Great",
		nameEl: "Όσιος Σισώης ο Μέγας",
		nameId: "Js. Sisoes Agung",
		julianMonth: 7,
		julianDay: 6,
	},
	{
		name: "Venerable Akakios who is mentioned in \"The Ladder of Virtues\"",
		nameEl: "Όσιος Ακάκιος ο εν τη Κλίμακι",
		nameId: "Js. Akakios yang disebutkan dalam \"Tangga Kebajikan\"",
		julianMonth: 7,
		julianDay: 7,
	},
	{
		name: "Holy Great Martyr Kyriake",
		nameEl: "Αγία Μεγαλομάρτυς Κυριακή",
		nameId: "Martir Agung Kudus Kyriake",
		julianMonth: 7,
		julianDay: 7,
	},
	{
		name: "Venerable Thomas of Maleum",
		nameEl: "Όσιος Θωμάς ο εν Μαλεώ",
		nameId: "Js. Tomas dari Maleum",
		julianMonth: 7,
		julianDay: 7,
	},
	{
		name: "Holy Great Martyr Procopius",
		nameEl: "Άγιος Μεγαλομάρτυς Προκόπιος",
		nameId: "Martir Agung Kudus Prokopius",
		julianMonth: 7,
		julianDay: 8,
	},
	{
		name: "Holy Hieromartyr Pancratios, Bishop of Taormina",
		nameEl: "Άγιος Ιερομάρτυς Παγκράτιος, Επίσκοπος Ταυρομενίας",
		nameId: "Hieromartir Kudus Pankratios, Uskup Taormina",
		julianMonth: 7,
		julianDay: 9,
	},
	{
		name: "Holy Great Martyr Euphemis",
		nameEl: "Αγία Μεγαλομάρτυς Ευφημία",
		nameId: "Martir Agung Kudus Euphemia",
		julianMonth: 7,
		julianDay: 11,
	},
	{
		name: "Holy Martyr Hilarios",
		nameEl: "Άγιος Μάρτυς Ιλάριος",
		nameId: "Martir Kudus Hilarios",
		julianMonth: 7,
		julianDay: 12,
	},
	{
		name: "Holy Martyr Proclos",
		nameEl: "Άγιος Μάρτυς Πρόκλος",
		nameId: "Martir Kudus Proklos",
		julianMonth: 7,
		julianDay: 12,
	},
	{
		name: "Synaxis of Archangel Gabriel",
		nameEl: "Σύναξις Αρχαγγέλου Γαβριήλ",
		nameId: "Sinaxi Malaikat Agung Gabriel",
		julianMonth: 7,
		julianDay: 13,
	},
	{
		name: "Venerable Stephen the Sabbaite",
		nameEl: "Όσιος Στέφανος ο Σαββαΐτης",
		nameId: "Js. Stefanus sang Sabbait",
		julianMonth: 7,
		julianDay: 13,
	},
	{
		name: "Holy Apostle Aquila",
		nameEl: "Άγιος Απόστολος Ακύλας",
		nameId: "Rasul Kudus Akuila",
		julianMonth: 7,
		julianDay: 14,
	},
	{
		name: "Veneration of Joseph the Confessor, Archbishop of Thessalonica",
		nameEl: "Μνήμη Ιωσήφ του Ομολογητού, Αρχιεπισκόπου Θεσσαλονίκης",
		nameId: "Peringatan Js. Yusuf sang Pengaku Iman, Uskup Agung Tesalonika",
		julianMonth: 7,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Julitta",
		nameEl: "Αγία Μάρτυς Ιουλίττα",
		nameId: "Martir Kudus Julitta",
		julianMonth: 7,
		julianDay: 15,
	},
	{
		name: "Holy Martyr Kerikos",
		nameEl: "Άγιος Μάρτυς Κήρυκος",
		nameId: "Martir Kudus Kerikos",
		julianMonth: 7,
		julianDay: 15,
	},
	{
		name: "Holy Hieromartyr Athenogenes",
		nameEl: "Άγιος Ιερομάρτυς Αθηνογένης",
		nameId: "Hieromartir Kudus Athenogenes",
		julianMonth: 7,
		julianDay: 16,
	},
	{
		name: "Holy Great Martyr Marina",
		nameEl: "Αγία Μεγαλομάρτυς Μαρίνα",
		nameId: "Martir Agung Kudus Marina",
		julianMonth: 7,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Aimilianos",
		nameEl: "Άγιος Μάρτυς Αιμιλιανός",
		nameId: "Martir Kudus Aimilianos",
		julianMonth: 7,
		julianDay: 18,
	},
	{
		name: "Venerable Dios",
		nameEl: "Όσιος Δίος",
		nameId: "Js. Dios",
		julianMonth: 7,
		julianDay: 19,
	},
	{
		name: "Venerable Macrina",
		nameEl: "Οσία Μακρίνα",
		nameId: "Js. Makrina",
		julianMonth: 7,
		julianDay: 19,
	},
	{
		name: "Prophet Elias the Thesbite",
		nameEl: "Προφήτης Ηλίας ο Θεσβίτης",
		nameId: "Nabi Elia sang Tisbit",
		julianMonth: 7,
		julianDay: 20,
	},
	{
		name: "Veneration of John, companion of Saint Simeon",
		nameEl: "Μνήμη Ιωάννου, συνοδοιπόρου του Αγίου Συμεών",
		nameId: "Peringatan Js. Yohanes, sahabat Js. Simeon",
		julianMonth: 7,
		julianDay: 21,
	},
	{
		name: "Venerable Simeon, a Fool for Christ's Sake",
		nameEl: "Όσιος Συμεών ο δια Χριστόν Σαλός",
		nameId: "Js. Simeon, Orang Bodoh demi Kristus",
		julianMonth: 7,
		julianDay: 21,
	},
	{
		name: "Holy Equal-to-the-Apostles Mary Magdalene",
		nameEl: "Αγία Ισαπόστολος Μαρία η Μαγδαληνή",
		nameId: "Kudus Setara-Rasul Maria Magdalena",
		julianMonth: 7,
		julianDay: 22,
	},
	{
		name: "Prophet Ezechiel",
		nameEl: "Προφήτης Ιεζεκιήλ",
		nameId: "Nabi Yehezkiel",
		julianMonth: 7,
		julianDay: 23,
	},
	{
		name: "Holy Great Martyr Christina",
		nameEl: "Αγία Μεγαλομάρτυς Χριστίνα",
		nameId: "Martir Agung Kudus Kristina",
		julianMonth: 7,
		julianDay: 24,
	},
	{
		name: "Holy Martyr Hermippos",
		nameEl: "Άγιος Μάρτυς Έρμιππος",
		nameId: "Martir Kudus Hermippos",
		julianMonth: 7,
		julianDay: 26,
	},
	{
		name: "Holy Martyr Hermocratos",
		nameEl: "Άγιος Μάρτυς Ερμοκράτης",
		nameId: "Martir Kudus Hermocratos",
		julianMonth: 7,
		julianDay: 26,
	},
	{
		name: "Holy Hieromartyr Hermolaus",
		nameEl: "Άγιος Ιερομάρτυς Ερμόλαος",
		nameId: "Hieromartir Kudus Hermolaus",
		julianMonth: 7,
		julianDay: 26,
	},
	{
		name: "Holy Hosiomartyr Paraskevia",
		nameEl: "Αγία Οσιομάρτυς Παρασκευή",
		nameId: "Hosiomartir Kudus Paraskevia",
		julianMonth: 7,
		julianDay: 26,
	},
	{
		name: "Holy Great Martyr and Healer Panteleemon",
		nameEl: "Άγιος Μεγαλομάρτυς και Ιαματικός Παντελεήμων",
		nameId: "Martir Agung dan Penyembuh Kudus Panteleemon",
		julianMonth: 7,
		julianDay: 27,
	},
	{
		name: "Holy Apostle Nicanor",
		nameEl: "Άγιος Απόστολος Νικάνωρ",
		nameId: "Rasul Kudus Nikanor",
		julianMonth: 7,
		julianDay: 28,
	},
	{
		name: "Holy Apostle Parmenas",
		nameEl: "Άγιος Απόστολος Παρμενάς",
		nameId: "Rasul Kudus Parmenas",
		julianMonth: 7,
		julianDay: 28,
	},
	{
		name: "Holy Apostle Prochoros",
		nameEl: "Άγιος Απόστολος Πρόχορος",
		nameId: "Rasul Kudus Prokhoros",
		julianMonth: 7,
		julianDay: 28,
	},
	{
		name: "Holy Martyr Callinicos",
		nameEl: "Άγιος Μάρτυς Καλλίνικος",
		nameId: "Martir Kudus Kallinikos",
		julianMonth: 7,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Theodota",
		nameEl: "Αγία Μάρτυς Θεοδότη",
		nameId: "Martir Kudus Theodota",
		julianMonth: 7,
		julianDay: 29,
	},
	{
		name: "Holy Apostle Andronicos",
		nameEl: "Άγιος Απόστολος Ανδρόνικος",
		nameId: "Rasul Kudus Andronikos",
		julianMonth: 7,
		julianDay: 30,
	},
	{
		name: "Holy Apostle Crescens",
		nameEl: "Άγιος Απόστολος Κρήσκης",
		nameId: "Rasul Kudus Crescens",
		julianMonth: 7,
		julianDay: 30,
	},
	{
		name: "Holy Apostle Epenetos",
		nameEl: "Άγιος Απόστολος Επαίνετος",
		nameId: "Rasul Kudus Epenetos",
		julianMonth: 7,
		julianDay: 30,
	},
	{
		name: "Holy Apostle Silas",
		nameEl: "Άγιος Απόστολος Σιλάς",
		nameId: "Rasul Kudus Silas",
		julianMonth: 7,
		julianDay: 30,
	},
	{
		name: "Holy Apostle Silvanos",
		nameEl: "Άγιος Απόστολος Σιλουανός",
		nameId: "Rasul Kudus Silvanus",
		julianMonth: 7,
		julianDay: 30,
	},
	{
		name: "Veneration of Eudocimos",
		nameEl: "Μνήμη Ευδοκίμου",
		nameId: "Peringatan Js. Eudocimos",
		julianMonth: 7,
		julianDay: 31,
	},

	// ─── AUGUST ───────────────────────────────────
	{
		name: "Veneration of Eleazar the Elder",
		nameEl: "Μνήμη Ελεαζάρου του Πρεσβυτέρου",
		nameId: "Peringatan Js. Eleazar sang Penatua",
		julianMonth: 8,
		julianDay: 1,
	},
	{
		name: "Holy Martyr Salome",
		nameEl: "Αγία Μάρτυς Σαλώμη",
		nameId: "Martir Kudus Salome",
		julianMonth: 8,
		julianDay: 1,
	},
	{
		name: "Holy Seven Machabee Martyrs",
		nameEl: "Άγιοι Επτά Μακκαβαίοι Μάρτυρες",
		nameId: "Tujuh Martir Kudus Makabe",
		julianMonth: 8,
		julianDay: 1,
	},
	{
		name: "Venerable Dalmatios",
		nameEl: "Όσιος Δαλμάτιος",
		nameId: "Js. Dalmatios",
		julianMonth: 8,
		julianDay: 3,
	},
	{
		name: "Venerable Faustos",
		nameEl: "Όσιος Φαύστος",
		nameId: "Js. Faustos",
		julianMonth: 8,
		julianDay: 3,
	},
	{
		name: "Venerable Isaac, Hegumen of the Monastery of Dalmaton",
		nameEl: "Όσιος Ισαάκ, Ηγούμενος Μονής Δαλμάτου",
		nameId: "Js. Ishak, Hegumen Biara Dalmaton",
		julianMonth: 8,
		julianDay: 3,
	},
	{
		name: "Holy Hosiomartyr Eudocia",
		nameEl: "Αγία Οσιομάρτυς Ευδοκία",
		nameId: "Hosiomartir Kudus Eudokia",
		julianMonth: 8,
		julianDay: 4,
	},
	{
		name: "Holy Martyr Eusignios",
		nameEl: "Άγιος Μάρτυς Ευσίγνιος",
		nameId: "Martir Kudus Eusignios",
		julianMonth: 8,
		julianDay: 5,
	},
	{
		name: "Holy Hosiomartyr Dometios",
		nameEl: "Άγιος Οσιομάρτυς Δομέτιος",
		nameId: "Hosiomartir Kudus Dometios",
		julianMonth: 8,
		julianDay: 7,
	},
	{
		name: "Veneration of Aimilianos the Confessor, Bishop of Cyzicus",
		nameEl: "Μνήμη Αιμιλιανού του Ομολογητού, Επισκόπου Κυζίκου",
		nameId: "Peringatan Js. Aimilianos sang Pengaku Iman, Uskup Kizikus",
		julianMonth: 8,
		julianDay: 8,
	},
	{
		name: "Holy Apostle Matthias",
		nameEl: "Άγιος Απόστολος Ματθίας",
		nameId: "Rasul Kudus Matias",
		julianMonth: 8,
		julianDay: 9,
	},
	{
		name: "Holy Martyr Laurence",
		nameEl: "Άγιος Μάρτυς Λαυρέντιος",
		nameId: "Martir Kudus Laurensius",
		julianMonth: 8,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Euplos",
		nameEl: "Άγιος Μάρτυς Εύπλος",
		nameId: "Martir Kudus Euplos",
		julianMonth: 8,
		julianDay: 11,
	},
	{
		name: "Holy Martyr Anicetos",
		nameEl: "Άγιος Μάρτυς Ανίκητος",
		nameId: "Martir Kudus Anicetos",
		julianMonth: 8,
		julianDay: 12,
	},
	{
		name: "Holy Martyr Photios",
		nameEl: "Άγιος Μάρτυς Φώτιος",
		nameId: "Martir Kudus Photios",
		julianMonth: 8,
		julianDay: 12,
	},
	{
		name: "Prophet Michea",
		nameEl: "Προφήτης Μιχαίας",
		nameId: "Nabi Mikha",
		julianMonth: 8,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Diomedes",
		nameEl: "Άγιος Μάρτυς Διομήδης",
		nameId: "Martir Kudus Diomedes",
		julianMonth: 8,
		julianDay: 16,
	},
	{
		name: "Holy Martyr Myron",
		nameEl: "Άγιος Μάρτυς Μύρων",
		nameId: "Martir Kudus Myron",
		julianMonth: 8,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Floros",
		nameEl: "Άγιος Μάρτυς Φλώρος",
		nameId: "Martir Kudus Floros",
		julianMonth: 8,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Lauros",
		nameEl: "Άγιος Μάρτυς Λαύρος",
		nameId: "Martir Kudus Lauros",
		julianMonth: 8,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Andrew the Leader of Armies",
		nameEl: "Άγιος Μάρτυς Ανδρέας ο Στρατηλάτης",
		nameId: "Martir Kudus Andreas sang Pemimpin Pasukan",
		julianMonth: 8,
		julianDay: 19,
	},
	{
		name: "Prophet Samuel",
		nameEl: "Προφήτης Σαμουήλ",
		nameId: "Nabi Samuel",
		julianMonth: 8,
		julianDay: 20,
	},
	{
		name: "Holy Martyr Bassa",
		nameEl: "Αγία Μάρτυς Βάσσα",
		nameId: "Martir Kudus Bassa",
		julianMonth: 8,
		julianDay: 21,
	},
	{
		name: "Holy Apostle Jude",
		nameEl: "Άγιος Απόστολος Ιούδας",
		nameId: "Rasul Kudus Yudas",
		julianMonth: 8,
		julianDay: 21,
	},
	{
		name: "Holy Apostle Thaddeus",
		nameEl: "Άγιος Απόστολος Θαδδαίος",
		nameId: "Rasul Kudus Tadeus",
		julianMonth: 8,
		julianDay: 21,
	},
	{
		name: "Holy Martyr Akindinos",
		nameEl: "Άγιος Μάρτυς Ακίνδυνος",
		nameId: "Martir Kudus Akindinos",
		julianMonth: 8,
		julianDay: 22,
	},
	{
		name: "Holy Martyr Severian",
		nameEl: "Άγιος Μάρτυς Σεβηριανός",
		nameId: "Martir Kudus Severian",
		julianMonth: 8,
		julianDay: 22,
	},
	{
		name: "Holy Martyr Theoprepes",
		nameEl: "Άγιος Μάρτυς Θεοπρέπης",
		nameId: "Martir Kudus Theoprepes",
		julianMonth: 8,
		julianDay: 22,
	},
	{
		name: "Holy Martyr Zeno",
		nameEl: "Άγιος Μάρτυς Ζήνων",
		nameId: "Martir Kudus Zeno",
		julianMonth: 8,
		julianDay: 22,
	},
	{
		name: "Holy Martyr Zoticos",
		nameEl: "Άγιος Μάρτυς Ζωτικός",
		nameId: "Martir Kudus Zotikos",
		julianMonth: 8,
		julianDay: 22,
	},
	{
		name: "Holy Martyr Luppos",
		nameEl: "Άγιος Μάρτυς Λούππος",
		nameId: "Martir Kudus Luppos",
		julianMonth: 8,
		julianDay: 23,
	},
	{
		name: "Holy Hieromartyr Eutyches",
		nameEl: "Άγιος Ιερομάρτυς Ευτυχής",
		nameId: "Hieromartir Kudus Eutyches",
		julianMonth: 8,
		julianDay: 24,
	},
	{
		name: "Holy Apostle Titus",
		nameEl: "Άγιος Απόστολος Τίτος",
		nameId: "Rasul Kudus Titus",
		julianMonth: 8,
		julianDay: 25,
	},
	{
		name: "Holy Martyr Adrian",
		nameEl: "Άγιος Μάρτυς Αδριανός",
		nameId: "Martir Kudus Adrian",
		julianMonth: 8,
		julianDay: 26,
	},
	{
		name: "Holy Martyr Natalia",
		nameEl: "Αγία Μάρτυς Ναταλία",
		nameId: "Martir Kudus Natalia",
		julianMonth: 8,
		julianDay: 26,
	},
	{
		name: "Venerable Poemen",
		nameEl: "Όσιος Ποιμήν",
		nameId: "Js. Poimen",
		julianMonth: 8,
		julianDay: 27,
	},
	{
		name: "Veneration of Augustine, Bishop of Hippo",
		nameEl: "Μνήμη Αυγουστίνου, Επισκόπου Ιππώνος",
		nameId: "Peringatan Js. Agustinus, Uskup Hippo",
		julianMonth: 8,
		julianDay: 28,
	},
	{
		name: "Venerable Moses the Ethiopian",
		nameEl: "Όσιος Μωυσής ο Αιθίοψ",
		nameId: "Js. Musa dari Etiopia",
		julianMonth: 8,
		julianDay: 28,
	},
	{
		name: "Veneration of Alexander, Archbishop of Constantinople",
		nameEl: "Μνήμη Αλεξάνδρου, Αρχιεπισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Alexander, Uskup Agung Konstantinopel",
		julianMonth: 8,
		julianDay: 30,
	},
	{
		name: "Veneration of John II, Archbishop of Constantinople",
		nameEl: "Μνήμη Ιωάννου Β', Αρχιεπισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Yohanes II, Uskup Agung Konstantinopel",
		julianMonth: 8,
		julianDay: 30,
	},
	{
		name: "Veneration of Paul the Younger, Archbishop of Constantinople",
		nameEl: "Μνήμη Παύλου του Νέου, Αρχιεπισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Paulus Muda, Uskup Agung Konstantinopel",
		julianMonth: 8,
		julianDay: 30,
	},

	// ─── SEPTEMBER ───────────────────────────────────
	{
		name: "Holy Martyr Aeithalas",
		nameEl: "Άγιος Μάρτυς Αειθαλάς",
		nameId: "Martir Kudus Aeithalas",
		julianMonth: 9,
		julianDay: 1,
	},
	{
		name: "Holy Martyr Ammon the Deacon",
		nameEl: "Άγιος Μάρτυς Άμμων ο Διάκονος",
		nameId: "Martir Kudus Ammon sang Diakon",
		julianMonth: 9,
		julianDay: 1,
	},
	{
		name: "Holy Martyr Callistos",
		nameEl: "Άγιος Μάρτυς Κάλλιστος",
		nameId: "Martir Kudus Kallistos",
		julianMonth: 9,
		julianDay: 1,
	},
	{
		name: "Holy Martyr Evodios",
		nameEl: "Άγιος Μάρτυς Ευόδιος",
		nameId: "Martir Kudus Evodios",
		julianMonth: 9,
		julianDay: 1,
	},
	{
		name: "Veneration of Josue, Son of Nun, Successor of Moses",
		nameEl: "Μνήμη Ιησού του Ναυή, Διαδόχου Μωυσέως",
		nameId: "Peringatan Js. Yosua bin Nun, Penerus Musa",
		julianMonth: 9,
		julianDay: 1,
	},
	{
		name: "Venerable Simeon the Stylite",
		nameEl: "Όσιος Συμεών ο Στυλίτης",
		nameId: "Js. Simeon sang Stylite",
		julianMonth: 9,
		julianDay: 1,
	},
	{
		name: "Forty Holy Women Martyrs",
		nameEl: "Άγιαι Τεσσαράκοντα Γυναίκες Μάρτυρες",
		nameId: "Empat Puluh Martir Wanita Kudus",
		julianMonth: 9,
		julianDay: 1,
	},
	{
		name: "Veneration of John the Faster, Patriarch of Constantinople",
		nameEl: "Μνήμη Ιωάννου του Νηστευτού, Πατριάρχου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Yohanes sang Berpuasa, Patriarkh Konstantinopel",
		julianMonth: 9,
		julianDay: 2,
	},
	{
		name: "Holy Martyr Mamas",
		nameEl: "Άγιος Μάρτυς Μάμας",
		nameId: "Martir Kudus Mamas",
		julianMonth: 9,
		julianDay: 2,
	},
	{
		name: "Holy Hieromartyr Anthimos, Bishop of Nicomedia",
		nameEl: "Άγιος Ιερομάρτυς Άνθιμος, Επίσκοπος Νικομηδείας",
		nameId: "Hieromartir Kudus Anthimos, Uskup Nikomedia",
		julianMonth: 9,
		julianDay: 3,
	},
	{
		name: "Venerable Theoktistos, companion in asceticism of the Great Euthymius",
		nameEl: "Όσιος Θεόκτιστος, συνασκητής του Μεγάλου Ευθυμίου",
		nameId: "Js. Theoktistos, rekan pertapaan Euthimius Agung",
		julianMonth: 9,
		julianDay: 3,
	},
	{
		name: "Holy Hieromartyr Babylas, Bishop of Antioch",
		nameEl: "Άγιος Ιερομάρτυς Βαβύλας, Επίσκοπος Αντιοχείας",
		nameId: "Hieromartir Kudus Babylas, Uskup Antiokhia",
		julianMonth: 9,
		julianDay: 4,
	},
	{
		name: "Prophet Moses the God-seer",
		nameEl: "Προφήτης Μωυσής ο Θεόπτης",
		nameId: "Nabi Musa sang Pelihat Allah",
		julianMonth: 9,
		julianDay: 4,
	},
	{
		name: "Prophet Zachary, Father of the Precursor",
		nameEl: "Προφήτης Ζαχαρίας, πατήρ του Προδρόμου",
		nameId: "Nabi Zakharia, Ayah sang Pendahulu",
		julianMonth: 9,
		julianDay: 5,
	},
	{
		name: "Holy Martyr Sozon",
		nameEl: "Άγιος Μάρτυς Σώζων",
		nameId: "Martir Kudus Sozon",
		julianMonth: 9,
		julianDay: 7,
	},
	{
		name: "Veneration of Righteous Joachim",
		nameEl: "Μνήμη Δικαίου Ιωακείμ",
		nameId: "Peringatan Js. Yoakim",
		julianMonth: 9,
		julianDay: 9,
	},
	{
		name: "Holy Martyr Severian",
		nameEl: "Άγιος Μάρτυς Σεβηριανός",
		nameId: "Martir Kudus Severian",
		julianMonth: 9,
		julianDay: 9,
	},
	{
		name: "Holy Martyr Menodora",
		nameEl: "Αγία Μάρτυς Μηνοδώρα",
		nameId: "Martir Kudus Menodora",
		julianMonth: 9,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Metrodora",
		nameEl: "Αγία Μάρτυς Μητροδώρα",
		nameId: "Martir Kudus Metrodora",
		julianMonth: 9,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Nymphodora",
		nameEl: "Αγία Μάρτυς Νυμφοδώρα",
		nameId: "Martir Kudus Nymphodora",
		julianMonth: 9,
		julianDay: 10,
	},
	{
		name: "Venerable Theodora of Alexandria",
		nameEl: "Οσία Θεοδώρα η εξ Αλεξανδρείας",
		nameId: "Js. Theodora dari Aleksandria",
		julianMonth: 9,
		julianDay: 11,
	},
	{
		name: "Holy Hieromartyr Autonomus",
		nameEl: "Άγιος Ιερομάρτυς Αυτόνομος",
		nameId: "Hieromartir Kudus Autonomus",
		julianMonth: 9,
		julianDay: 12,
	},
	{
		name: "Holy Hieromartyr Cornelius the Centurion",
		nameEl: "Άγιος Ιερομάρτυς Κορνήλιος ο Εκατόνταρχος",
		nameId: "Hieromartir Kudus Kornelius sang Perwira",
		julianMonth: 9,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Nikita",
		nameEl: "Άγιος Μάρτυς Νικήτας",
		nameId: "Martir Kudus Nikita",
		julianMonth: 9,
		julianDay: 15,
	},
	{
		name: "Holy Great Martyr Euphemis",
		nameEl: "Αγία Μεγαλομάρτυς Ευφημία",
		nameId: "Martir Agung Kudus Euphemia",
		julianMonth: 9,
		julianDay: 16,
	},
	{
		name: "Holy Martyr Charity (Agape)",
		nameEl: "Αγία Μάρτυς Αγάπη",
		nameId: "Martir Kudus Kasih (Agape)",
		julianMonth: 9,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Elpis (Hope)",
		nameEl: "Αγία Μάρτυς Ελπίς",
		nameId: "Martir Kudus Harapan (Elpis)",
		julianMonth: 9,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Faith (Pistis)",
		nameEl: "Αγία Μάρτυς Πίστις",
		nameId: "Martir Kudus Iman (Pistis)",
		julianMonth: 9,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Hope (Elpis)",
		nameEl: "Αγία Μάρτυς Ελπίς",
		nameId: "Martir Kudus Harapan (Elpis)",
		julianMonth: 9,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Pistis (Faith)",
		nameEl: "Αγία Μάρτυς Πίστις",
		nameId: "Martir Kudus Iman (Pistis)",
		julianMonth: 9,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Sophia (Wisdom)",
		nameEl: "Αγία Μάρτυς Σοφία",
		nameId: "Martir Kudus Kebijaksanaan (Sophia)",
		julianMonth: 9,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Wisdom (Sophia)",
		nameEl: "Αγία Μάρτυς Σοφία",
		nameId: "Martir Kudus Kebijaksanaan (Sofia)",
		julianMonth: 9,
		julianDay: 17,
	},
	{
		name: "Venerable Eumenios the Wonderworker, Bishop of Gortyna",
		nameEl: "Όσιος Ευμένιος ο Θαυματουργός, Επίσκοπος Γορτύνης",
		nameId: "Js. Eumenios sang Pembuat Mukjizat, Uskup Gortyna",
		julianMonth: 9,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Dorymedes",
		nameEl: "Άγιος Μάρτυς Δορυμέδων",
		nameId: "Martir Kudus Dorymedes",
		julianMonth: 9,
		julianDay: 19,
	},
	{
		name: "Holy Martyr Sabbatios",
		nameEl: "Άγιος Μάρτυς Σαββάτιος",
		nameId: "Martir Kudus Sabbatios",
		julianMonth: 9,
		julianDay: 19,
	},
	{
		name: "Holy Great Martyr Eustathios",
		nameEl: "Άγιος Μεγαλομάρτυς Ευστάθιος",
		nameId: "Martir Agung Kudus Eustathios",
		julianMonth: 9,
		julianDay: 20,
	},
	{
		name: "Holy Martyr Theopistis",
		nameEl: "Αγία Μάρτυς Θεοπίστη",
		nameId: "Martir Kudus Theopistis",
		julianMonth: 9,
		julianDay: 20,
	},
	{
		name: "Holy Martyr Theopistos",
		nameEl: "Άγιος Μάρτυς Θεόπιστος",
		nameId: "Martir Kudus Theopistos",
		julianMonth: 9,
		julianDay: 20,
	},
	{
		name: "Holy Apostle Quadratus of Magnesia",
		nameEl: "Άγιος Απόστολος Κοδράτος ο εν Μαγνησία",
		nameId: "Rasul Kudus Kuadratus dari Magnesia",
		julianMonth: 9,
		julianDay: 21,
	},
	{
		name: "Holy Hieromartyr Phocas, Bishop of Sinope",
		nameEl: "Άγιος Ιερομάρτυς Φωκάς, Επίσκοπος Σινώπης",
		nameId: "Hieromartir Kudus Phokas, Uskup Sinope",
		julianMonth: 9,
		julianDay: 22,
	},
	{
		name: "Holy Protomartyr Thecla",
		nameEl: "Αγία Πρωτομάρτυς Θέκλα",
		nameId: "Protomartir Kudus Thekla",
		julianMonth: 9,
		julianDay: 24,
	},
	{
		name: "Venerable Euphrosyne the Righteous",
		nameEl: "Οσία Ευφροσύνη η Δικαία",
		nameId: "Js. Euphrosyne yang Benar",
		julianMonth: 9,
		julianDay: 25,
	},
	{
		name: "Holy Apostle and Evangelist John the Theologian",
		nameEl: "Άγιος Απόστολος και Ευαγγελιστής Ιωάννης ο Θεολόγος",
		nameId: "Rasul dan Penginjil Kudus Yohanes sang Teolog",
		julianMonth: 9,
		julianDay: 26,
	},
	{
		name: "Holy Martyr Callistratos",
		nameEl: "Άγιος Μάρτυς Καλλίστρατος",
		nameId: "Martir Kudus Kallistratos",
		julianMonth: 9,
		julianDay: 27,
	},
	{
		name: "Venerable Chariton the Confessor",
		nameEl: "Όσιος Χαρίτων ο Ομολογητής",
		nameId: "Js. Khariton sang Pengaku Iman",
		julianMonth: 9,
		julianDay: 28,
	},
	{
		name: "Venerable Cypriacos the Anchorite",
		nameEl: "Όσιος Κυπριακός ο Αναχωρητής",
		nameId: "Js. Kypriacos sang Pertapa",
		julianMonth: 9,
		julianDay: 29,
	},
	{
		name: "Holy Hieromartyr Gregory, Bishop of Greater Armenia",
		nameEl: "Άγιος Ιερομάρτυς Γρηγόριος, Επίσκοπος Μεγάλης Αρμενίας",
		nameId: "Hieromartir Kudus Gregorius, Uskup Armenia Raya",
		julianMonth: 9,
		julianDay: 30,
	},

	// ─── OCTOBER ───────────────────────────────────
	{
		name: "Holy Apostle Ananias",
		nameEl: "Άγιος Απόστολος Ανανίας",
		nameId: "Rasul Kudus Ananias",
		julianMonth: 10,
		julianDay: 1,
	},
	{
		name: "Venerable Roman the Hymnographer",
		nameEl: "Όσιος Ρωμανός ο Μελωδός",
		nameId: "Js. Romanus sang Pembuat Himne",
		julianMonth: 10,
		julianDay: 1,
	},
	{
		name: "Holy Martyr Aphthonios",
		nameEl: "Άγιος Μάρτυς Αφθόνιος",
		nameId: "Martir Kudus Aphthonios",
		julianMonth: 10,
		julianDay: 2,
	},
	{
		name: "Holy Hieromartyr Cyprian",
		nameEl: "Άγιος Ιερομάρτυς Κυπριανός",
		nameId: "Hieromartir Kudus Kyprian",
		julianMonth: 10,
		julianDay: 2,
	},
	{
		name: "Holy Martyr Elpidiphoros",
		nameEl: "Άγιος Μάρτυς Ελπιδηφόρος",
		nameId: "Martir Kudus Elpidiphoros",
		julianMonth: 10,
		julianDay: 2,
	},
	{
		name: "Holy Martyr Justina",
		nameEl: "Αγία Μάρτυς Ιουστίνα",
		nameId: "Martir Kudus Justina",
		julianMonth: 10,
		julianDay: 2,
	},
	{
		name: "Holy Martyr Pegasios",
		nameEl: "Άγιος Μάρτυς Πηγάσιος",
		nameId: "Martir Kudus Pegasios",
		julianMonth: 10,
		julianDay: 2,
	},
	{
		name: "Holy Hieromartyr Dionysius the Areopagite",
		nameEl: "Άγιος Ιερομάρτυς Διονύσιος ο Αρεοπαγίτης",
		nameId: "Hieromartir Kudus Dionisius sang Areopagit",
		julianMonth: 10,
		julianDay: 3,
	},
	{
		name: "Holy Martyr Joseph the Priest",
		nameEl: "Άγιος Μάρτυς Ιωσήφ ο Ιερεύς",
		nameId: "Martir Kudus Yusuf sang Imam",
		julianMonth: 10,
		julianDay: 3,
	},
	{
		name: "Holy Hieromartyr Hermeus the Priest",
		nameEl: "Άγιος Ιερομάρτυς Ερμαίος ο Ιερεύς",
		nameId: "Hieromartir Kudus Hermeus sang Imam",
		julianMonth: 10,
		julianDay: 4,
	},
	{
		name: "Veneration of Hierotheos, Bishop of Athens",
		nameEl: "Μνήμη Ιεροθέου, Επισκόπου Αθηνών",
		nameId: "Peringatan Js. Hierotheos, Uskup Athena",
		julianMonth: 10,
		julianDay: 4,
	},
	{
		name: "Venerable Joannikios the Great",
		nameEl: "Όσιος Ιωαννίκιος ο Μέγας",
		nameId: "Js. Yoannikios Agung",
		julianMonth: 10,
		julianDay: 4,
	},
	{
		name: "Holy Hieromartyr Nicander, Bishop of Myra",
		nameEl: "Άγιος Ιερομάρτυς Νίκανδρος, Επίσκοπος Μύρων",
		nameId: "Hieromartir Kudus Nikander, Uskup Myra",
		julianMonth: 10,
		julianDay: 4,
	},
	{
		name: "Holy Martyr Charitina",
		nameEl: "Αγία Μάρτυς Χαριτίνα",
		nameId: "Martir Kudus Kharitina",
		julianMonth: 10,
		julianDay: 5,
	},
	{
		name: "Holy Martyr Episteme",
		nameEl: "Αγία Μάρτυς Επιστήμη",
		nameId: "Martir Kudus Episteme",
		julianMonth: 10,
		julianDay: 5,
	},
	{
		name: "Holy Martyr Galaktion",
		nameEl: "Άγιος Μάρτυς Γαλακτίων",
		nameId: "Martir Kudus Galaktion",
		julianMonth: 10,
		julianDay: 5,
	},
	{
		name: "Veneration of Paul the Confessor, Bishop of Constantinople",
		nameEl: "Μνήμη Παύλου του Ομολογητού, Επισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Paulus sang Pengaku Iman, Uskup Konstantinopel",
		julianMonth: 10,
		julianDay: 6,
	},
	{
		name: "Holy Apostle Thomas",
		nameEl: "Άγιος Απόστολος Θωμάς",
		nameId: "Rasul Kudus Tomas",
		julianMonth: 10,
		julianDay: 6,
	},
	{
		name: "Holy Martyr Bacchus",
		nameEl: "Άγιος Μάρτυς Βάκχος",
		nameId: "Martir Kudus Bacchus",
		julianMonth: 10,
		julianDay: 7,
	},
	{
		name: "Venerable Lazarus the Wonderworker",
		nameEl: "Όσιος Λάζαρος ο Θαυματουργός",
		nameId: "Js. Lazarus sang Pembuat Mukjizat",
		julianMonth: 10,
		julianDay: 7,
	},
	{
		name: "Holy Martyr Sergius",
		nameEl: "Άγιος Μάρτυς Σέργιος",
		nameId: "Martir Kudus Sergius",
		julianMonth: 10,
		julianDay: 7,
	},
	{
		name: "Synaxis of Archangel Michael and all the Bodiless Powers of Heaven",
		nameEl: "Σύναξις Αρχαγγέλου Μιχαήλ και πασών των Ασωμάτων Δυνάμεων",
		nameId: "Sinaxi Malaikat Agung Mikhael dan seluruh Kuasa Surgawi yang Tak Berwujud",
		julianMonth: 10,
		julianDay: 8,
	},
	{
		name: "Venerable Pelagia",
		nameEl: "Οσία Πελαγία",
		nameId: "Js. Pelagia",
		julianMonth: 10,
		julianDay: 8,
	},
	{
		name: "Synaxis of the Bodiless Powers",
		nameEl: "Σύναξις των Ασωμάτων Δυνάμεων",
		nameId: "Sinaxi Kuasa-kuasa yang Tak Berwujud",
		julianMonth: 10,
		julianDay: 8,
	},
	{
		name: "Venerable Andronicos",
		nameEl: "Όσιος Ανδρόνικος",
		nameId: "Js. Andronikos",
		julianMonth: 10,
		julianDay: 9,
	},
	{
		name: "Venerable Athanasia",
		nameEl: "Οσία Αθανασία",
		nameId: "Js. Athanasia",
		julianMonth: 10,
		julianDay: 9,
	},
	{
		name: "Holy Apostle James, brother of the Lord, Bishop of Jerusalem",
		nameEl: "Άγιος Απόστολος Ιάκωβος, Αδελφόθεος, Επίσκοπος Ιεροσολύμων",
		nameId: "Rasul Kudus Yakobus, Saudara Tuhan, Uskup Yerusalem",
		julianMonth: 10,
		julianDay: 9,
	},
	{
		name: "Venerable Matrona",
		nameEl: "Οσία Ματρώνα",
		nameId: "Js. Matrona",
		julianMonth: 10,
		julianDay: 9,
	},
	{
		name: "Holy Martyr Onesiphoros",
		nameEl: "Άγιος Μάρτυς Ονησιφόρος",
		nameId: "Martir Kudus Onesiphoros",
		julianMonth: 10,
		julianDay: 9,
	},
	{
		name: "Holy Martyr Porphyrios",
		nameEl: "Άγιος Μάρτυς Πορφύριος",
		nameId: "Martir Kudus Porphyrios",
		julianMonth: 10,
		julianDay: 9,
	},
	{
		name: "Holy Apostle Erastos",
		nameEl: "Άγιος Απόστολος Έραστος",
		nameId: "Rasul Kudus Erastos",
		julianMonth: 10,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Eulampia",
		nameEl: "Αγία Μάρτυς Ευλαμπία",
		nameId: "Martir Kudus Eulampia",
		julianMonth: 10,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Eulampios",
		nameEl: "Άγιος Μάρτυς Ευλάμπιος",
		nameId: "Martir Kudus Eulampios",
		julianMonth: 10,
		julianDay: 10,
	},
	{
		name: "Holy Apostle Olympus",
		nameEl: "Άγιος Απόστολος Ολυμπάς",
		nameId: "Rasul Kudus Olympas",
		julianMonth: 10,
		julianDay: 10,
	},
	{
		name: "Holy Apostle Orestes",
		nameEl: "Άγιος Απόστολος Ορέστης",
		nameId: "Rasul Kudus Orestes",
		julianMonth: 10,
		julianDay: 10,
	},
	{
		name: "Holy Apostle Quartus",
		nameEl: "Άγιος Απόστολος Κούαρτος",
		nameId: "Rasul Kudus Kuartus",
		julianMonth: 10,
		julianDay: 10,
	},
	{
		name: "Holy Apostle Rodionos",
		nameEl: "Άγιος Απόστολος Ροδίων",
		nameId: "Rasul Kudus Rodionos",
		julianMonth: 10,
		julianDay: 10,
	},
	{
		name: "Holy Apostle Sosipatros",
		nameEl: "Άγιος Απόστολος Σωσίπατρος",
		nameId: "Rasul Kudus Sosipatros",
		julianMonth: 10,
		julianDay: 10,
	},
	{
		name: "Holy Apostle Tertios",
		nameEl: "Άγιος Απόστολος Τέρτιος",
		nameId: "Rasul Kudus Tertios",
		julianMonth: 10,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Menas",
		nameEl: "Άγιος Μάρτυς Μηνάς",
		nameId: "Martir Kudus Menas",
		julianMonth: 10,
		julianDay: 11,
	},
	{
		name: "Holy Apostle Philip, one of the Seven Deacons",
		nameEl: "Άγιος Απόστολος Φίλιππος, εις εκ των Επτά Διακόνων",
		nameId: "Rasul Kudus Filipus, salah satu dari Tujuh Diakon",
		julianMonth: 10,
		julianDay: 11,
	},
	{
		name: "Holy Martyr Stephanida",
		nameEl: "Αγία Μάρτυς Στεφανίδα",
		nameId: "Martir Kudus Stephanida",
		julianMonth: 10,
		julianDay: 11,
	},
	{
		name: "Venerable Theodore the Studite",
		nameEl: "Όσιος Θεόδωρος ο Στουδίτης",
		nameId: "Js. Theodorus sang Studit",
		julianMonth: 10,
		julianDay: 11,
	},
	{
		name: "Venerable Theophanes the Confessor",
		nameEl: "Όσιος Θεοφάνης ο Ομολογητής",
		nameId: "Js. Theofanes sang Pengaku Iman",
		julianMonth: 10,
		julianDay: 11,
	},
	{
		name: "Holy Martyr Victor",
		nameEl: "Άγιος Μάρτυς Βίκτωρ",
		nameId: "Martir Kudus Viktor",
		julianMonth: 10,
		julianDay: 11,
	},
	{
		name: "Holy Martyr Vincent",
		nameEl: "Άγιος Μάρτυς Βικέντιος",
		nameId: "Martir Kudus Vikensius",
		julianMonth: 10,
		julianDay: 11,
	},
	{
		name: "Holy Martyr Andronicos",
		nameEl: "Άγιος Μάρτυς Ανδρόνικος",
		nameId: "Martir Kudus Andronikos",
		julianMonth: 10,
		julianDay: 12,
	},
	{
		name: "Veneration of John the Almsgiver, Archbishop of Alexandria",
		nameEl: "Μνήμη Ιωάννου του Ελεήμονος, Αρχιεπισκόπου Αλεξανδρείας",
		nameId: "Peringatan Js. Yohanes sang Pemberi Sedekah, Uskup Agung Aleksandria",
		julianMonth: 10,
		julianDay: 12,
	},
	{
		name: "Venerable Nilus the Sinaite",
		nameEl: "Όσιος Νείλος ο Σιναΐτης",
		nameId: "Js. Nilus dari Sinai",
		julianMonth: 10,
		julianDay: 12,
	},
	{
		name: "Holy Martyr Probus",
		nameEl: "Άγιος Μάρτυς Πρόβος",
		nameId: "Martir Kudus Probus",
		julianMonth: 10,
		julianDay: 12,
	},
	{
		name: "Holy Martyr Tarachos",
		nameEl: "Άγιος Μάρτυς Τάραχος",
		nameId: "Martir Kudus Tarakhos",
		julianMonth: 10,
		julianDay: 12,
	},
	{
		name: "Holy Martyr Agathonice",
		nameEl: "Αγία Μάρτυς Αγαθονίκη",
		nameId: "Martir Kudus Agathonice",
		julianMonth: 10,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Carpos",
		nameEl: "Άγιος Μάρτυς Κάρπος",
		nameId: "Martir Kudus Karpos",
		julianMonth: 10,
		julianDay: 13,
	},
	{
		name: "John Chrysostom, Archbishop of Constantinople",
		nameEl: "Ιωάννης ο Χρυσόστομος, Αρχιεπίσκοπος Κωνσταντινουπόλεως",
		nameId: "Js. Yohanes Krisostomus, Uskup Agung Konstantinopel",
		julianMonth: 10,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Papylos",
		nameEl: "Άγιος Μάρτυς Πάπυλος",
		nameId: "Martir Kudus Papylos",
		julianMonth: 10,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Celsios",
		nameEl: "Άγιος Μάρτυς Κέλσιος",
		nameId: "Martir Kudus Celsios",
		julianMonth: 10,
		julianDay: 14,
	},
	{
		name: "Venerable Cosmas the Hagiopolite, Bishop of Maiuma",
		nameEl: "Όσιος Κοσμάς ο Αγιοπολίτης, Επίσκοπος Μαϊουμά",
		nameId: "Js. Kosmas sang Hagiopolite, Uskup Maiuma",
		julianMonth: 10,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Gervasios",
		nameEl: "Άγιος Μάρτυς Γερβάσιος",
		nameId: "Martir Kudus Gervasios",
		julianMonth: 10,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Nazarios",
		nameEl: "Άγιος Μάρτυς Ναζάριος",
		nameId: "Martir Kudus Nazarios",
		julianMonth: 10,
		julianDay: 14,
	},
	{
		name: "Holy Apostle Philip",
		nameEl: "Άγιος Απόστολος Φίλιππος",
		nameId: "Rasul Kudus Filipus",
		julianMonth: 10,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Prostasios",
		nameEl: "Άγιος Μάρτυς Προτάσιος",
		nameId: "Martir Kudus Prostasios",
		julianMonth: 10,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Gourias",
		nameEl: "Άγιος Μάρτυς Γουρίας",
		nameId: "Martir Kudus Gourias",
		julianMonth: 10,
		julianDay: 15,
	},
	{
		name: "Holy Hieromartyr Lucian",
		nameEl: "Άγιος Ιερομάρτυς Λουκιανός",
		nameId: "Hieromartir Kudus Lukian",
		julianMonth: 10,
		julianDay: 15,
	},
	{
		name: "Holy Martyr Samonas",
		nameEl: "Άγιος Μάρτυς Σαμωνάς",
		nameId: "Martir Kudus Samonas",
		julianMonth: 10,
		julianDay: 15,
	},
	{
		name: "Holy Martyr Longinus the Centurion",
		nameEl: "Άγιος Μάρτυς Λογγίνος ο Εκατόνταρχος",
		nameId: "Martir Kudus Longinus sang Perwira",
		julianMonth: 10,
		julianDay: 16,
	},
	{
		name: "Holy Apostle and Evangelist Matthew",
		nameEl: "Άγιος Απόστολος και Ευαγγελιστής Ματθαίος",
		nameId: "Rasul dan Penginjil Kudus Matius",
		julianMonth: 10,
		julianDay: 16,
	},
	{
		name: "Holy Hosiomartyr Andrew of Crete",
		nameEl: "Άγιος Οσιομάρτυς Ανδρέας ο εν Κρήτη",
		nameId: "Hosiomartir Kudus Andreas dari Kreta",
		julianMonth: 10,
		julianDay: 17,
	},
	{
		name: "Veneration of Gregory the Wonderworker, Bishop of Neocaesarea",
		nameEl: "Μνήμη Γρηγορίου του Θαυματουργού, Επισκόπου Νεοκαισαρείας",
		nameId: "Peringatan Js. Gregorius sang Pembuat Mukjizat, Uskup Neokaisarea",
		julianMonth: 10,
		julianDay: 17,
	},
	{
		name: "Prophet Osee",
		nameEl: "Προφήτης Ωσηέ",
		nameId: "Nabi Hosea",
		julianMonth: 10,
		julianDay: 17,
	},
	{
		name: "Holy Apostle and Evangelist Luke",
		nameEl: "Άγιος Απόστολος και Ευαγγελιστής Λουκάς",
		nameId: "Rasul dan Penginjil Kudus Lukas",
		julianMonth: 10,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Plato",
		nameEl: "Άγιος Μάρτυς Πλάτων",
		nameId: "Martir Kudus Plato",
		julianMonth: 10,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Roman",
		nameEl: "Άγιος Μάρτυς Ρωμανός",
		nameId: "Martir Kudus Romanus",
		julianMonth: 10,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Barlaam",
		nameEl: "Άγιος Μάρτυς Βαρλαάμ",
		nameId: "Martir Kudus Barlaam",
		julianMonth: 10,
		julianDay: 19,
	},
	{
		name: "Prophet Joel",
		nameEl: "Προφήτης Ιωήλ",
		nameId: "Nabi Yoel",
		julianMonth: 10,
		julianDay: 19,
	},
	{
		name: "Holy Martyr Varus",
		nameEl: "Άγιος Μάρτυς Ουάρος",
		nameId: "Martir Kudus Varus",
		julianMonth: 10,
		julianDay: 19,
	},
	{
		name: "Holy Great Martyr Artemios",
		nameEl: "Άγιος Μεγαλομάρτυς Αρτέμιος",
		nameId: "Martir Agung Kudus Artemios",
		julianMonth: 10,
		julianDay: 20,
	},
	{
		name: "Venerable Gregory the Decapolite",
		nameEl: "Όσιος Γρηγόριος ο Δεκαπολίτης",
		nameId: "Js. Gregorius sang Dekapolit",
		julianMonth: 10,
		julianDay: 20,
	},
	{
		name: "Veneration of Proclos, Archbishop of Constantinople",
		nameEl: "Μνήμη Πρόκλου, Αρχιεπισκόπου Κωνσταντινουπόλεως",
		nameId: "Peringatan Js. Proklos, Uskup Agung Konstantinopel",
		julianMonth: 10,
		julianDay: 20,
	},
	{
		name: "Venerable Hilarion the Great",
		nameEl: "Όσιος Ιλαρίων ο Μέγας",
		nameId: "Js. Hilarion Agung",
		julianMonth: 10,
		julianDay: 21,
	},
	{
		name: "Veneration of Abercius, Bishop of Hierapolis",
		nameEl: "Μνήμη Αβερκίου, Επισκόπου Ιεραπόλεως",
		nameId: "Peringatan Js. Aberkius, Uskup Hierapolis",
		julianMonth: 10,
		julianDay: 22,
	},
	{
		name: "Holy Apostle Apphias",
		nameEl: "Άγιος Απόστολος Απφίας",
		nameId: "Rasul Kudus Apphias",
		julianMonth: 10,
		julianDay: 22,
	},
	{
		name: "Holy Apostle Archippos",
		nameEl: "Άγιος Απόστολος Άρχιππος",
		nameId: "Rasul Kudus Arkhippos",
		julianMonth: 10,
		julianDay: 22,
	},
	{
		name: "Holy Martyr Cecilia",
		nameEl: "Αγία Μάρτυς Κικιλία",
		nameId: "Martir Kudus Cecilia",
		julianMonth: 10,
		julianDay: 22,
	},
	{
		name: "Holy Apostle Onesimos",
		nameEl: "Άγιος Απόστολος Ονήσιμος",
		nameId: "Rasul Kudus Onesimus",
		julianMonth: 10,
		julianDay: 22,
	},
	{
		name: "Holy Apostle Philemon",
		nameEl: "Άγιος Απόστολος Φιλήμων",
		nameId: "Rasul Kudus Filemon",
		julianMonth: 10,
		julianDay: 22,
	},
	{
		name: "Holy Martyr Tiburtios",
		nameEl: "Άγιος Μάρτυς Τιβούρτιος",
		nameId: "Martir Kudus Tiburtios",
		julianMonth: 10,
		julianDay: 22,
	},
	{
		name: "Holy Martyr Valerian",
		nameEl: "Άγιος Μάρτυς Βαλεριανός",
		nameId: "Martir Kudus Valerian",
		julianMonth: 10,
		julianDay: 22,
	},
	{
		name: "Veneration of Gregory, Bishop of Agrigentum",
		nameEl: "Μνήμη Γρηγορίου, Επισκόπου Ακραγαντίνων",
		nameId: "Peringatan Js. Gregorius, Uskup Agrigentum",
		julianMonth: 10,
		julianDay: 23,
	},
	{
		name: "Holy Apostle James, brother of the Lord, Bishop of Jerusalem",
		nameEl: "Άγιος Απόστολος Ιάκωβος, Αδελφόθεος, Επίσκοπος Ιεροσολύμων",
		nameId: "Rasul Kudus Yakobus, Saudara Tuhan, Uskup Yerusalem",
		julianMonth: 10,
		julianDay: 23,
	},
	{
		name: "Holy Great Martyr Arethas",
		nameEl: "Άγιος Μεγαλομάρτυς Αρέθας",
		nameId: "Martir Agung Kudus Arethas",
		julianMonth: 10,
		julianDay: 24,
	},
	{
		name: "Holy Hieromartyr Peter, Bishop of Alexandria",
		nameEl: "Άγιος Ιερομάρτυς Πέτρος, Επίσκοπος Αλεξανδρείας",
		nameId: "Hieromartir Kudus Petrus, Uskup Aleksandria",
		julianMonth: 10,
		julianDay: 24,
	},
	{
		name: "Holy Great Martyr Catherine",
		nameEl: "Αγία Μεγαλομάρτυς Αικατερίνη",
		nameId: "Martir Agung Kudus Ekaterina",
		julianMonth: 10,
		julianDay: 25,
	},
	{
		name: "Holy Martyr Marcian",
		nameEl: "Άγιος Μάρτυς Μαρκιανός",
		nameId: "Martir Kudus Markian",
		julianMonth: 10,
		julianDay: 25,
	},
	{
		name: "Holy Martyr Martyrios",
		nameEl: "Άγιος Μάρτυς Μαρτύριος",
		nameId: "Martir Kudus Martyrios",
		julianMonth: 10,
		julianDay: 25,
	},
	{
		name: "Holy Great Martyr Mercury",
		nameEl: "Άγιος Μεγαλομάρτυς Μερκούριος",
		nameId: "Martir Agung Kudus Merkurius",
		julianMonth: 10,
		julianDay: 25,
	},
	{
		name: "Holy Great Martyr Demetrius",
		nameEl: "Άγιος Μεγαλομάρτυς Δημήτριος",
		nameId: "Martir Agung Kudus Demetrius",
		julianMonth: 10,
		julianDay: 26,
	},
	{
		name: "Holy Great Martyr James the Persian",
		nameEl: "Άγιος Μεγαλομάρτυς Ιάκωβος ο Πέρσης",
		nameId: "Martir Agung Kudus Yakobus dari Persia",
		julianMonth: 10,
		julianDay: 27,
	},
	{
		name: "Holy Martyr Nestor",
		nameEl: "Άγιος Μάρτυς Νέστωρ",
		nameId: "Martir Kudus Nestor",
		julianMonth: 10,
		julianDay: 27,
	},
	{
		name: "Holy Martyr Irenarchos",
		nameEl: "Άγιος Μάρτυς Ειρήναρχος",
		nameId: "Martir Kudus Irenarchos",
		julianMonth: 10,
		julianDay: 28,
	},
	{
		name: "Holy Martyr Neonila",
		nameEl: "Αγία Μάρτυς Νεονίλλα",
		nameId: "Martir Kudus Neonila",
		julianMonth: 10,
		julianDay: 28,
	},
	{
		name: "Venerable Stephen the Sabbaite",
		nameEl: "Όσιος Στέφανος ο Σαββαΐτης",
		nameId: "Js. Stefanus sang Sabbait",
		julianMonth: 10,
		julianDay: 28,
	},
	{
		name: "Holy Hosiomartyr Stephen the Younger",
		nameEl: "Όσιομάρτυς Στέφανος ο Νέος",
		nameId: "Osiomartir Kudus Stefanus sang Muda",
		julianMonth: 10,
		julianDay: 28,
	},
	{
		name: "Holy Martyr Terence",
		nameEl: "Άγιος Μάρτυς Τερέντιος",
		nameId: "Martir Kudus Terensius",
		julianMonth: 10,
		julianDay: 28,
	},
	{
		name: "Venerable Abramios",
		nameEl: "Όσιος Αβράμιος",
		nameId: "Js. Abramios",
		julianMonth: 10,
		julianDay: 29,
	},
	{
		name: "Holy Hosiomartyr Anastasia the Healer, Pharmacolytria",
		nameEl: "Αγία Οσιομάρτυς Αναστασία η Φαρμακολύτρια",
		nameId: "Hosiomartir Kudus Anastasia sang Penyembuh, Farmakolytria",
		julianMonth: 10,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Paramonos",
		nameEl: "Άγιος Μάρτυς Παράμονος",
		nameId: "Martir Kudus Paramonos",
		julianMonth: 10,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Philomenos",
		nameEl: "Άγιος Μάρτυς Φιλούμενος",
		nameId: "Martir Kudus Philomenos",
		julianMonth: 10,
		julianDay: 29,
	},
	{
		name: "Holy Martyr Zenobia",
		nameEl: "Αγία Μάρτυς Ζηνοβία",
		nameId: "Martir Kudus Zenobia",
		julianMonth: 10,
		julianDay: 30,
	},
	{
		name: "Holy Hieromartyr Zenobios",
		nameEl: "Ιερομάρτυς Ζηνόβιος",
		nameId: "Hieromartir Kudus Zenobios",
		julianMonth: 10,
		julianDay: 30,
	},
	{
		name: "Holy Apostle Amplias",
		nameEl: "Άγιος Απόστολος Αμπλίας",
		nameId: "Rasul Kudus Amplias",
		julianMonth: 10,
		julianDay: 31,
	},
	{
		name: "Holy Apostle Apollos",
		nameEl: "Άγιος Απόστολος Απολλώς",
		nameId: "Rasul Kudus Apollos",
		julianMonth: 10,
		julianDay: 31,
	},
	{
		name: "Holy Apostle Aristobulos",
		nameEl: "Άγιος Απόστολος Αριστόβουλος",
		nameId: "Rasul Kudus Aristobulos",
		julianMonth: 10,
		julianDay: 31,
	},
	{
		name: "Holy Martyr Epimachos",
		nameEl: "Άγιος Μάρτυς Επίμαχος",
		nameId: "Martir Kudus Epimachos",
		julianMonth: 10,
		julianDay: 31,
	},
	{
		name: "Holy Apostle Narcissus",
		nameEl: "Άγιος Απόστολος Νάρκισσος",
		nameId: "Rasul Kudus Narcissus",
		julianMonth: 10,
		julianDay: 31,
	},
	{
		name: "Holy Apostle Stachys",
		nameEl: "Άγιος Απόστολος Στάχυς",
		nameId: "Rasul Kudus Stakhis",
		julianMonth: 10,
		julianDay: 31,
	},
	{
		name: "Holy Apostle Urban",
		nameEl: "Άγιος Απόστολος Ουρβανός",
		nameId: "Rasul Kudus Urbanus",
		julianMonth: 10,
		julianDay: 31,
	},

	// ─── NOVEMBER ───────────────────────────────────
	{
		name: "Holy Martyr Akindinos",
		nameEl: "Άγιος Μάρτυς Ακίνδυνος",
		nameId: "Martir Kudus Akindinos",
		julianMonth: 11,
		julianDay: 2,
	},
	{
		name: "Holy Martyr Anempodistos",
		nameEl: "Άγιος Μάρτυς Ανεμπόδιστος",
		nameId: "Martir Kudus Anempodistos",
		julianMonth: 11,
		julianDay: 2,
	},
	{
		name: "Holy Martyr Aeithalas the Deacon",
		nameEl: "Άγιος Μάρτυς Αειθαλάς ο Διάκονος",
		nameId: "Martir Kudus Aeithalas sang Diakon",
		julianMonth: 11,
		julianDay: 3,
	},
	{
		name: "Holy Martyr Akepsimas",
		nameEl: "Άγιος Μάρτυς Ακεψιμάς",
		nameId: "Martir Kudus Akepsimas",
		julianMonth: 11,
		julianDay: 3,
	},
	{
		name: "Holy Martyr Abibos",
		nameEl: "Άγιος Μάρτυς Άβιβος",
		nameId: "Martir Kudus Abibos",
		julianMonth: 11,
		julianDay: 15,
	},
	{
		name: "Prophet Abdia",
		nameEl: "Προφήτης Αβδιού",
		nameId: "Nabi Abdia",
		julianMonth: 11,
		julianDay: 19,
	},
	{
		name: "Veneration of Amphilochios, Bishop of Iconium",
		nameEl: "Μνήμη Αμφιλοχίου, Επισκόπου Ικονίου",
		nameId: "Peringatan Js. Amfilokhios, Uskup Ikonium",
		julianMonth: 11,
		julianDay: 23,
	},
	{
		name: "Holy Hieromartyr Clement, Pope of Rome",
		nameEl: "Άγιος Ιερομάρτυς Κλήμης, Πάπας Ρώμης",
		nameId: "Hieromartir Kudus Klemens, Paus Roma",
		julianMonth: 11,
		julianDay: 24,
	},
	{
		name: "Venerable Alypios the Stylite",
		nameEl: "Όσιος Αλύπιος ο Κιονίτης",
		nameId: "Js. Alypios sang Stylite",
		julianMonth: 11,
		julianDay: 26,
	},
	{
		name: "Holy Apostle Andrew the First-called",
		nameEl: "Άγιος Απόστολος Ανδρέας ο Πρωτόκλητος",
		nameId: "Rasul Kudus Andreas yang Pertama Dipanggil",
		julianMonth: 11,
		julianDay: 30,
	},

	// ─── DECEMBER ───────────────────────────────────
	{
		name: "Prophet Nahum",
		nameEl: "Προφήτης Ναούμ",
		nameId: "Nabi Nahum",
		julianMonth: 12,
		julianDay: 1,
	},
	{
		name: "Prophet Habacuc",
		nameEl: "Προφήτης Αββακούμ",
		nameId: "Nabi Habakuk",
		julianMonth: 12,
		julianDay: 2,
	},
	{
		name: "Prophet Sophonia",
		nameEl: "Προφήτης Σοφονίας",
		nameId: "Nabi Zefanya",
		julianMonth: 12,
		julianDay: 3,
	},
	{
		name: "Holy Great Martyr Barbara",
		nameEl: "Αγία Μεγαλομάρτυς Βαρβάρα",
		nameId: "Martir Agung Kudus Barbara",
		julianMonth: 12,
		julianDay: 4,
	},
	{
		name: "Venerable John Damascene",
		nameEl: "Όσιος Ιωάννης ο Δαμασκηνός",
		nameId: "Js. Yohanes Damaskinus",
		julianMonth: 12,
		julianDay: 4,
	},
	{
		name: "Venerable Sabbas the Sanctified",
		nameEl: "Όσιος Σάββας ο Ηγιασμένος",
		nameId: "Js. Sabbas yang Dikuduskan",
		julianMonth: 12,
		julianDay: 5,
	},
	{
		name: "Nicholas the Wonderworker, Archbishop of Myra in Lycia",
		nameEl: "Νικόλαος ο Θαυματουργός, Αρχιεπίσκοπος Μύρων της Λυκίας",
		nameId: "Js. Nikolaus sang Pembuat Mukjizat, Uskup Agung Myra di Lykia",
		julianMonth: 12,
		julianDay: 6,
	},
	{
		name: "Veneration of Ambrose, Bishop of Milan",
		nameEl: "Μνήμη Αμβροσίου, Επισκόπου Μεδιολάνων",
		nameId: "Peringatan Js. Ambrosius, Uskup Milan",
		julianMonth: 12,
		julianDay: 7,
	},
	{
		name: "Venerable Patapios",
		nameEl: "Όσιος Παταπίος",
		nameId: "Js. Patapios",
		julianMonth: 12,
		julianDay: 8,
	},
	{
		name: "Veneration of Righteous Ann, Mother of the Theotokos",
		nameEl: "Μνήμη Δικαίας Άννης, Μητρός της Θεοτόκου",
		nameId: "Peringatan Js. Anna, Ibu Theotokos",
		julianMonth: 12,
		julianDay: 9,
	},
	{
		name: "Conception of Righteous Ann, Mother of the Theotokos",
		nameEl: "Σύλληψις της Δικαίας Άννης, Μητρός της Θεοτόκου",
		nameId: "Pembuahan Js. Anna, Ibu Theotokos",
		julianMonth: 12,
		julianDay: 9,
	},
	{
		name: "Holy Martyr Eugraphos",
		nameEl: "Άγιος Μάρτυς Εύγραφος",
		nameId: "Martir Kudus Eugraphos",
		julianMonth: 12,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Hermogenes",
		nameEl: "Άγιος Μάρτυς Ερμογένης",
		nameId: "Martir Kudus Hermogenes",
		julianMonth: 12,
		julianDay: 10,
	},
	{
		name: "Holy Martyr Menas",
		nameEl: "Άγιος Μάρτυς Μηνάς",
		nameId: "Martir Kudus Menas",
		julianMonth: 12,
		julianDay: 10,
	},
	{
		name: "Venerable Daniel the Stylite",
		nameEl: "Όσιος Δανιήλ ο Στυλίτης",
		nameId: "Js. Daniel sang Stylite",
		julianMonth: 12,
		julianDay: 11,
	},
	{
		name: "Veneration of Spiridon, Bishop of Tremithus",
		nameEl: "Μνήμη Σπυρίδωνος, Επισκόπου Τριμυθούντος",
		nameId: "Peringatan Js. Spiridon, Uskup Tremithus",
		julianMonth: 12,
		julianDay: 12,
	},
	{
		name: "Holy Martyr Auxentios",
		nameEl: "Άγιος Μάρτυς Αυξέντιος",
		nameId: "Martir Kudus Auxentios",
		julianMonth: 12,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Eugene",
		nameEl: "Άγιος Μάρτυς Ευγένιος",
		nameId: "Martir Kudus Eugenius",
		julianMonth: 12,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Eustatios",
		nameEl: "Άγιος Μάρτυς Ευστάτιος",
		nameId: "Martir Kudus Eustatios",
		julianMonth: 12,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Lucy",
		nameEl: "Αγία Μάρτυς Λουκία",
		nameId: "Martir Kudus Lucia",
		julianMonth: 12,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Mardarios",
		nameEl: "Άγιος Μάρτυς Μαρδάριος",
		nameId: "Martir Kudus Mardarios",
		julianMonth: 12,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Orestes",
		nameEl: "Άγιος Μάρτυς Ορέστης",
		nameId: "Martir Kudus Orestes",
		julianMonth: 12,
		julianDay: 13,
	},
	{
		name: "Holy Martyr Apollonios",
		nameEl: "Άγιος Μάρτυς Απολλώνιος",
		nameId: "Martir Kudus Apollonios",
		julianMonth: 12,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Callinicos",
		nameEl: "Άγιος Μάρτυς Καλλίνικος",
		nameId: "Martir Kudus Kallinikos",
		julianMonth: 12,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Leucios",
		nameEl: "Άγιος Μάρτυς Λεύκιος",
		nameId: "Martir Kudus Leucios",
		julianMonth: 12,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Philemon",
		nameEl: "Άγιος Μάρτυς Φιλήμων",
		nameId: "Martir Kudus Filemon",
		julianMonth: 12,
		julianDay: 14,
	},
	{
		name: "Holy Martyr Thyrsos",
		nameEl: "Άγιος Μάρτυς Θύρσος",
		nameId: "Martir Kudus Thirsos",
		julianMonth: 12,
		julianDay: 14,
	},
	{
		name: "Holy Hieromartyr Eleutherios, Bishop of Illyricum",
		nameEl: "Άγιος Ιερομάρτυς Ελευθέριος, Επίσκοπος Ιλλυρικού",
		nameId: "Hieromartir Kudus Eleutherios, Uskup Ilyrikum",
		julianMonth: 12,
		julianDay: 15,
	},
	{
		name: "Prophet Aggai",
		nameEl: "Προφήτης Αγγαίος",
		nameId: "Nabi Hagai",
		julianMonth: 12,
		julianDay: 16,
	},
	{
		name: "Holy Youth Anania, one of the Three Youths",
		nameEl: "Άγιος Ανανίας, εις εκ των Τριών Παίδων",
		nameId: "Pemuda Kudus Anania, salah satu dari Tiga Pemuda",
		julianMonth: 12,
		julianDay: 17,
	},
	{
		name: "Holy Youth Azaria, one of the Three Youths",
		nameEl: "Άγιος Αζαρίας, εις εκ των Τριών Παίδων",
		nameId: "Pemuda Kudus Azaria, salah satu dari Tiga Pemuda",
		julianMonth: 12,
		julianDay: 17,
	},
	{
		name: "Prophet Daniel",
		nameEl: "Προφήτης Δανιήλ",
		nameId: "Nabi Daniel",
		julianMonth: 12,
		julianDay: 17,
	},
	{
		name: "Holy Youth Misael, one of the Three Youths",
		nameEl: "Άγιος Μισαήλ, εις εκ των Τριών Παίδων",
		nameId: "Pemuda Kudus Misael, salah satu dari Tiga Pemuda",
		julianMonth: 12,
		julianDay: 17,
	},
	{
		name: "Holy Martyr Sebastian",
		nameEl: "Άγιος Μάρτυς Σεβαστιανός",
		nameId: "Martir Kudus Sebastianus",
		julianMonth: 12,
		julianDay: 18,
	},
	{
		name: "Holy Martyr Boniface",
		nameEl: "Άγιος Μάρτυς Βονιφάτιος",
		nameId: "Martir Kudus Bonifasius",
		julianMonth: 12,
		julianDay: 19,
	},
	{
		name: "Holy Hieromartyr Ignatius the God-Bearer",
		nameEl: "Άγιος Ιερομάρτυς Ιγνάτιος ο Θεοφόρος",
		nameId: "Hieromartir Kudus Ignatius sang Pemikul Allah",
		julianMonth: 12,
		julianDay: 20,
	},
	{
		name: "Holy Martyr Juliana of Nicomedia",
		nameEl: "Αγία Μάρτυς Ιουλιανή η εν Νικομηδεία",
		nameId: "Martir Kudus Juliana dari Nikomedia",
		julianMonth: 12,
		julianDay: 21,
	},
	{
		name: "Holy Hosiomartyr Anastasia the Healer, Pharmacolytria",
		nameEl: "Αγία Οσιομάρτυς Αναστασία η Φαρμακολύτρια",
		nameId: "Hosiomartir Kudus Anastasia sang Penyembuh, Farmakolytria",
		julianMonth: 12,
		julianDay: 22,
		julianYear: 291,
	},
	{
		name: "Holy Martyr Agathopos",
		nameEl: "Άγιος Μάρτυς Αγαθόπους",
		nameId: "Martir Kudus Agathopos",
		julianMonth: 12,
		julianDay: 23,
	},
	{
		name: "Basil the Great, Archbishop of Caesarea of Cappadocia",
		nameEl: "Βασίλειος ο Μέγας, Αρχιεπίσκοπος Καισαρείας Καππαδοκίας",
		nameId: "Js. Basilius Agung, Uskup Agung Kaisarea Kapadokia",
		julianMonth: 12,
		julianDay: 23,
	},
	{
		name: "Holy Martyr Eunician",
		nameEl: "Άγιος Μάρτυς Ευνικιανός",
		nameId: "Martir Kudus Eunician",
		julianMonth: 12,
		julianDay: 23,
	},
	{
		name: "Holy Martyr Euporos",
		nameEl: "Άγιος Μάρτυς Εύπορος",
		nameId: "Martir Kudus Euporos",
		julianMonth: 12,
		julianDay: 23,
	},
	{
		name: "Holy Martyr Evarestos",
		nameEl: "Άγιος Μάρτυς Εβάρεστος",
		nameId: "Martir Kudus Evarestos",
		julianMonth: 12,
		julianDay: 23,
	},
	{
		name: "Holy Martyr Gelasios",
		nameEl: "Άγιος Μάρτυς Γελάσιος",
		nameId: "Martir Kudus Gelasios",
		julianMonth: 12,
		julianDay: 23,
	},
	{
		name: "Holy Martyr Pompios",
		nameEl: "Άγιος Μάρτυς Πόμπιος",
		nameId: "Martir Kudus Pompios",
		julianMonth: 12,
		julianDay: 23,
	},
	{
		name: "Holy Martyr Saturninus",
		nameEl: "Άγιος Μάρτυς Σατουρνίνος",
		nameId: "Martir Kudus Saturninus",
		julianMonth: 12,
		julianDay: 23,
	},
	{
		name: "Holy Martyr Theodulos",
		nameEl: "Άγιος Μάρτυς Θεόδουλος",
		nameId: "Martir Kudus Theodulos",
		julianMonth: 12,
		julianDay: 23,
	},
	{
		name: "Holy Martyr Zoticos",
		nameEl: "Άγιος Μάρτυς Ζωτικός",
		nameId: "Martir Kudus Zotikos",
		julianMonth: 12,
		julianDay: 23,
	},
	{
		name: "Holy Hosiomartyr Eugenia",
		nameEl: "Αγία Οσιομάρτυς Ευγενία",
		nameId: "Hosiomartir Kudus Eugenia",
		julianMonth: 12,
		julianDay: 24,
	},
	{
		name: "Prophet-King David",
		nameEl: "Προφητάναξ Δαβίδ",
		nameId: "Nabi-Raja Daud",
		julianMonth: 12,
		julianDay: 26,
	},
	{
		name: "Holy Hieromartyr Euthymius, Metropolitan of Sardes",
		nameEl: "Άγιος Ιερομάρτυς Ευθύμιος, Μητροπολίτης Σάρδεων",
		nameId: "Hieromartir Kudus Euthymius, Metropolitan Sardes",
		julianMonth: 12,
		julianDay: 26,
	},
	{
		name: "Holy Apostle James, brother of the Lord, Bishop of Jerusalem",
		nameEl: "Άγιος Απόστολος Ιάκωβος, Αδελφόθεος, Επίσκοπος Ιεροσολύμων",
		nameId: "Rasul Kudus Yakobus, Saudara Tuhan, Uskup Yerusalem",
		julianMonth: 12,
		julianDay: 26,
	},
	{
		name: "Veneration of Righteous Joseph the Betrothed, Guardian of the Virgin",
		nameEl: "Μνήμη Δικαίου Ιωσήφ του Μνήστορος, Προστάτου της Παρθένου",
		nameId: "Peringatan Js. Yusuf sang Tunangan, Pelindung Perawan",
		julianMonth: 12,
		julianDay: 26,
	},
	{
		name: "Holy Protomartyr and Archdeacon Stephen",
		nameEl: "Άγιος Πρωτομάρτυς και Αρχιδιάκονος Στέφανος",
		nameId: "Protomartir dan Arkidiakon Kudus Stefanus",
		julianMonth: 12,
		julianDay: 27,
	},
	{
		name: "Venerable Theodore the Scarred",
		nameEl: "Όσιος Θεόδωρος ο Γραπτός",
		nameId: "Js. Theodorus sang Bertanda",
		julianMonth: 12,
		julianDay: 27,
	},
	{
		name: "Holy Infants killed by Herod in Bethlehem",
		nameEl: "Άγια Νήπια τα υπό Ηρώδου αναιρεθέντα εν Βηθλεέμ",
		nameId: "Bayi-bayi Kudus yang dibunuh oleh Herodes di Betlehem",
		julianMonth: 12,
		julianDay: 29,
	},
	{
		name: "Venerable Markellos",
		nameEl: "Όσιος Μάρκελλος",
		nameId: "Js. Markellos",
		julianMonth: 12,
		julianDay: 29,
	},
	{
		name: "Veneration of Anysia of Thessalonica",
		nameEl: "Μνήμη Ανυσίας της Θεσσαλονίκης",
		nameId: "Peringatan Js. Anysia dari Tesalonika",
		julianMonth: 12,
		julianDay: 30,
	},
	{
		name: "Venerable Zoticos the Educator of Orphans",
		nameEl: "Όσιος Ζωτικός ο Ορφανοτρόφος",
		nameId: "Js. Zotikos sang Pengasuh Yatim",
		julianMonth: 12,
		julianDay: 30,
	},
	{
		name: "Venerable Melania the Roman",
		nameEl: "Οσία Μελάνη η Ρωμαία",
		nameId: "Js. Melania dari Roma",
		julianMonth: 12,
		julianDay: 31,
	},
]
